<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
            Product Edit <small>edit product content</small>
        </h3>
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <i class="fa fa-home"></i>
                <a href="/">Home</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="/search">Content</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="">Product Edit</a>
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>
<!-- END PAGE HEADER-->
<!-- BEGIN PAGE CONTENT-->
<div class="row">
<form id="generalForm" action="/form" method="POST">
<div class="col-md-12">
<div class="portlet">
<div class="portlet-title">
    <div class="caption">
        <i class="fa fa-shopping-cart"></i><a href="http://focuscamera.com/<?=$this->data->getUrlKey()?>.html" target="_blank"><?=$this->data->getTitle()?></a>
    </div>

    <div class="actions btn-set">
        <button type="button" name="back" class="btn default"><i class="fa fa-angle-left"></i> Back</button>
        <button class="btn green" id="submitForm"><i class="fa fa-check" ></i> Save</button>
        <!--<input class="btn default" value="Save" type="submit">-->
    </div>
</div>
<div class="portlet-body">
<div class="tabbable">
<ul class="nav nav-tabs">
    <li class="active">
        <a href="#tab_general" data-toggle="tab">
            General </a>
    </li>
    <li>
        <a href="#tab_acessories" data-toggle="tab">
            Acessories </a>
    </li>
    <li>
        <a href="#tab_images" data-toggle="tab">
            Images <span class="badge badge-success">
											3 </span></a>
    </li>
    <li>
        <a href="#tab_categories" data-toggle="tab">
            Catagories
        </a>
    </li>
</ul>






<div class="tab-content no-space">
<div class="tab-pane active" id="tab_general">
<br /> <br />
<!-- General Tab info-->


<!-- Standard-->
<div class="portlet box blue">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>Standard
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse">
            </a>

        </div>
    </div>


    <div class="portlet-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3" for="general_sku">SKU</label>
                    <div class="col-md-9">
                        <input type="text" class="form-control" name="sku" value="<?= $this->data->getSku(); ?>" placeholder="SKU" style="width:140px" required/>
                        <span class="help-block"></span>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3" for="general_sku">Name</label>
                    <div class="col-md-9">
                        <input type="text" class="form-control"  name="title" placeholder="Title" value="<?=$this->data->getTitle()?>" required/>
                        <span class="help-block"></span>
                    </div>
                </div>
            </div>

        </div>

        <br />
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3" for="general_sku">Inventory</label>
                    <div class="col-md-9">
                        <input type="text" class="form-control" name="inventory"  placeholder="Inventory" style="width:140px" value="<?=$this->data->getInventory()?>" required/>
                        <span class="help-block"></span>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3" for="general_sku">URL Key</label>
                    <div class="col-md-9">
                        <input type="text" class="form-control" name="urlkey" placeholder="URL Key" value="<?=$this->data->getUrlKey()?>"  required/>
                        <span class="help-block"></span>
                    </div>
                </div>
            </div>

        </div>

        <br />
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3">Status</label>
                    <div class="col-md-9">
                        <select class="form-control input-medium" name="status">
                            <option value="0" <?= $this->data->getStatus() == 0 ? 'selected' :''  ?>>Status Not Set</option>
                            <option value="1" <?= $this->data->getStatus() == 1 ? 'selected' :''  ?>>Enabled</option>
                            <option value="2" <?= $this->data->getStatus() == 2 ? 'selected' :''  ?>>Disabled</option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3">Manufacturer</label>
                    <div class="col-md-9">
                        <select class="form-control input-medium" id="manufacturerDropdown" data-placeholder="No Manufacturer Set" name="manufacturer">
                            <option value="<?= array_keys(current($this->data->getManufacturer())); ?>" selected><?= current($this->data->getManufacturer()); ?></option>
                        </select>
                    </div>
                </div>
            </div>

        </div>

        <br />
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3" for="general_sku">Visibility</label>
                    <div class="col-md-9">
                        <select class="form-control input-medium" data-placeholder="No Visitility Set" name="visibility">
                            <option value=""></option>
                            <option value="1" <?= $this->data->getVisibility() == 1 ? 'selected' :''?>>Not Visible Indivdually</option>
                            <option value="2" <?= $this->data->getVisibility() == 2 ? 'selected' :''?>>Catalog</option>
                            <option value="3" <?= $this->data->getVisibility() == 3 ? 'selected' :''?>>Search</option>
                            <option value="4" <?= $this->data->getVisibility() == 4 ? 'selected' :''?>>Catalog, Search</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3">Brand</label>
                    <div class="col-md-9">
                        <select class="form-control input-medium" id="brandDropdown" data-placeholder="No Brand Set" name="brand">
                            <option value="<?= array_keys(current($this->data->getBrand())); ?>" selected><?= current($this->data->getBrand()); ?></option>
                        </select>
                    </div>
                </div>
            </div>

        </div>

        <br />
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3" for="general_sku">Condition</label>
                    <div class="col-md-9">
                        <select class="form-control input-medium" data-placeholder="No Condition Set" name="condition">
                            <option value=""></option>
                            <option value="1332" <?= $this->data->getCondition() == 1332 ? 'selected' :''?> >New</option>
                            <option value="1331" <?= $this->data->getCondition() == 1331 ? 'selected' :''?> >Refurbished</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3" for="general_sku">Tax Class</label>
                    <div class="col-md-9">
                        <select class="form-control input-medium" data-placeholder="Select..." name="taxClass">

                            <option value="0" <?= $this->data->getTaxClass() == 0 ? 'selected' :''?> >None</option>
                            <option value="1" <?= $this->data->getTaxClass() == 1 ? 'selected' :''?> >Default</option>
                            <option value="2" <?= $this->data->getTaxClass() == 2 ? 'selected' :''?> >Taxable Goods</option>
                            <option value="4" <?= $this->data->getTaxClass() == 3 ? 'selected' :''?> >Shipping</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3" for="general_sku">Custom Stock Status</label>
                    <div class="col-md-9">
                        <select class="form-control input-medium" data-placeholder="Select..." name="stockStatus">
                            <option value="0" <?= $this->data->getStockStatus() == 0 ? 'selected' :''?> > </option>
                            <option value="3756" <?= $this->data->getStockStatus() == 3756 ? 'selected' :''?> >Pre-Order Only </option>
                            <option value="4265" <?= $this->data->getStockStatus() == 4265 ? 'selected' :''?> >Call to Order</option>
                            <option value="3784" <?= $this->data->getStockStatus() == 3784 ? 'selected' :''?> >Ships in 5-7 Days</option>
                            <option value="3755" <?= $this->data->getStockStatus() == 3755 ? 'selected' :''?> >Ships in 3-4 Days</option>
                        </select>
                    </div>
                </div>
            </div>


            <div class="col-md-6">
                <div class="col-md-4">
                    <div class="form-group">
                        <div class="checker">
                            <span><input name = "orginalContent" type="checkbox"></span>
                        </div>
                        Original Content
                    </div>
                </div><div class="col-md-4">
                    <div class="form-group">
                        <div class="checker">
                            <span><input name="contentReviewed" type="checkbox"></span>
                        </div>
                        Content Reviewed
                    </div>
                </div>
            </div>

        </div>




    </div>
</div>


<br /><br />
<!--------------------Pricing-------------------->
<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>Pricing
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse">
            </a>

        </div>
    </div>


    <div class="portlet-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3" for="price">Price</label>
                    <div class="col-md-9">
                        <input type="text" class="form-control" name="price" placeholder="Price" style="width:140px" value="<?=$this->data->getPrice();?>" required/>
                        <span class="help-block"></span>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3" for="cost">Cost</label>
                    <div class="col-md-9">
                        <input type="text" class="form-control"  name="cost" placeholder="cost" style="width:140px" value="<?=$this->data->getCost(); ?>"/>
                        <span class="help-block"></span>
                    </div>
                </div>
            </div>

        </div>


        <br />
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3" for="inventory">MSRP</label>
                    <div class="col-md-9">
                        <input type="text" class="form-control" name="msrp"  placeholder="MSRP" style="width:140px"/>
                        <span class="help-block"></span>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3">Map Display</label>
                    <div class="col-md-4">
                        <select class="form-control input-medium" name="mapDisplay" data-placeholder="Select...">
                            <option value=""></option>
                            <option value="2" <?= $this->data->getMapDisplay() == 2 ? 'selected' :''?> >In Cart</option>
                            <option value="3" <?= $this->data->getMapDisplay() == 3 ? 'selected' :''?> >Before Order Confirmation</option>
                            <option value="1" <?= $this->data->getMapDisplay() == 1 ? 'selected' :''?> >On Gesture</option>
                            <option value="4" <?= $this->data->getMapDisplay() == 4 ? 'selected' :''?> >Use config</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>



        <br />
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3">Rebate Price</label>
                    <div class="col-md-9">
                        <input type="text" class="form-control" name="rebatePrice"  placeholder="Rebate" style="width:140px" value="<?=$rebatePrice = is_null($this->data->getRebatePrice())? 0:  $this->data-getRebatePrice() ?>">
                        <span class="help-block"></span>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3">Start Date -End Date (Rebate)</label>
                    <div class="col-md-4">
                        <div class="input-group" id="rebate">
                            <input type="text" class="form-control" name="rebatedates" value="<?=$rebateStartEndDate = is_null($this->data->getRebateStartEndDate())? '' : $this->data->getRebateStartEndDate()?>">
												<span class="input-group-btn">
												<button class="btn default date-range-toggle" type="button"><i class="fa fa-calendar"></i></button>
												</span>
                        </div>
                    </div>
                </div>
            </div>

        </div>

        <br />
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3">Special Price</label>
                    <div class="col-md-9">
                        <input type="text" class="form-control"  name="specialprice" placeholder="Special Price" style="width:140px" value="<?=$specialPrice = is_null($this->data->getSpecialPrice())? 0:  $this->data-getSpecialPrice() ?>"/>
                        <span class="help-block"></span>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3">Start Date -End Date (Special Price)</label>
                    <div class="col-md-4">
                        <div class="input-group" id="special">
                            <input type="text" class="form-control" name="specialrebatedates" value="<?=$specialStartEndDate = is_null($this->data->getSpecialStartEndDate())? '' : $this->data->getSpecialStartEndDate()?>">
												<span class="input-group-btn">
												<button class="btn default date-range-toggle" type="button"><i class="fa fa-calendar"></i></button>
												</span>
                        </div>
                    </div>
                </div>
            </div>

        </div>

        <br />
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3" for="general_sku">Mail in rebate</label>
                    <div class="col-md-9">
                        <input type="text" class="form-control" name="mailinrebate"  placeholder="Mail in Rebate" style="width:140px" value="<?=$mailinPrice = is_null($this->data->getMailInRebate())? 0:  $this->data->getMailInRebate() ?>">
                        <span class="help-block"></span>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3">Start Date -End Date (Mail in rebate)</label>
                    <div class="col-md-4">
                        <div class="input-group" id="mailin">
                            <input type="text" name="mailinrebatedates" class="form-control" value="<?=$mailStartEndDate = is_null($this->data->getMailInStartEndDate())? '' : $this->data->getMailInStartEndDate()?>">
												<span class="input-group-btn">
												<button class="btn default date-range-toggle" type="button"><i class="fa fa-calendar"></i></button>
												</span>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>
</div>




<!---Description-->
<div class="portlet box blue tabbable">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>Description
        </div>
    </div>


    <div class="portlet-body">
        <div class="portlet-tabs">
            <ul class="nav nav-tabs">
                <li>
                    <a href="#portlet_includesfree" data-toggle="tab">
                        Includes Free </a>
                </li>
                <li>
                    <a href="#portlet_inbox" data-toggle="tab">
                        In Box </a>
                </li>
                <li>
                    <a href="#portlet_sDescription" data-toggle="tab">
                        Short Description </a>
                </li>
                <li>
                    <a href="#portlet_description" data-toggle="tab"> Description</a>
                </li>
                <li  class="active">
                    <a href="#portlet_metaData" data-toggle="tab"> MetaData</a>
                </li>
            </ul>
            <div class="row">
                <div class="tab-content">

                <!-- MetaData-->
                <div class="tab-pane active" id="portlet_metaData">
                    <!-- MetaKeywords-->
                    <div class = "row col-md-11">
                        <div class="form-body">
                            <div class="form-group col-md-11">
                                <label class="control-label col-md-3" for="metaKeywords">MetaKeywords:</label>
                                <div class="col-md-6">
                                    <input type="text" class="form-control" name="metaKeyword" placeholder="MetaKeywords" value="<?php $this->data->getMetaKeywords(); ?>"/>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br/><br/><br/><br/>


                    <!-- MetaTitle-->
                    <div class = "row col-md-11">
                        <div class="form-body">
                            <div class="form-group col-md-11">
                                <label class="control-label col-md-3" for="metaKeywords">MetaTitle:</label>
                                <div class="col-md-6">
                                    <input type="text" class="form-control" name="metaTitle" placeholder="MetaTitle" value="<?php $this->data->getMetaTitle(); ?>"/>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br/><br/><br/><br/>




                    <!-- metaDescription-->
                    <div class="row col-md-11">
                        <div class="form-body">
                            <div class="form-group col-md-11">
                                <label class="control-label col-md-3">MetaDescription:</label>
                                <div class="col-md-11">
                                    <textarea id="metadescriptionwys" class="form-control" name ="metadescription" rows="20" style = "height: 500px;"> <?= $this->data->getMetaDescription(); ?> </textarea>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>







                <!-- Description-->
                <div class="tab-pane" id="portlet_description">
                    <div class="form-body">
                        <div class="form-group col-md-11">
                            <label class="control-label col-md-3">Description</label>
                            <div class="col-md-11">
                            <textarea id="descriptionwys" class="form-control" name ="description" rows="20" style = "height: 500px;"> <?= $this->data->getDescription(); ?> </textarea>
                                </div>
                        </div>

                    </div>
                </div>

                <!--Short Description-->
                <div class="tab-pane" id="portlet_sDescription">
                    <div class="form-body">
                        <div class="form-group col-md-11">
                            <label class="control-label col-md-3">Short Description</label>
                            <div class="col-md-11">
                                <textarea  id="shortdescriptionwys" class="form-control" name="shortDescription" rows="6" style = "height: 500px;"> <?= $this->data->getShortDescription(); ?> </textarea>
                            </div>
                        </div>

                    </div>
                </div>

                <!--In Box-->
                <div class="tab-pane" id="portlet_inbox">
                    <div class="form-body">
                        <div class="form-group col-md-11">
                            <label class="control-label col-md-3">In Box</label>
                            <div class="col-md-11">
                                <textarea id="inboxwys" class="form-control" name = "inBox" rows="6" style = "height: 500px;"> <?= $this->data->getInBox(); ?> </textarea>
                            </div>
                        </div>

                    </div>
                </div>

                <!--Includes Free-->
                <div class="tab-pane" id="portlet_includesfree">
                    <div class="form-body">
                        <div class="form-group col-md-11">
                            <label class="control-label col-md-3" for="searchTerms">Includes Free</label>
                            <div class="col-md-11">
                                <textarea class="wysihtml5 form-control" rows="6" name="includesFree" style = "height: 500px;"> <?php $this->data->getIncludesFree() ?> </textarea>
                            </div>
                        </div>

                    </div>
                </div>





            </div><!--end tab content-->

            </div>
         </div>
     </div>
</div>
</div>



</form>



<div class="tab-pane" id="tab_acessories">
    <!-- Acessories-->

    <div class="row">
        <div class="col-md-6">
            <!-- Related products-->
            <div class="portlet box blue">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-gift"></i>Acessories
                    </div>
                    <div class="tools">
                        <a href="javascript:;" class="collapse">
                        </a>

                    </div>
                </div>


                <div class="portlet-body">
                    <div class="row">
                        <div class="col-md-11">
                            <div class="table-toolbar">
                                <div class="btn-group">
                                    <a class="btn green" data-toggle="modal" href="#acessoryModal">
                                        Add Acessory <i class="fa fa-plus"></i></a>
                                </div>
                             </div>
                            <table class="table table-striped table-bordered table-hover" id="acessoriesDisplay">
                                <thead>
                                <tr><th>id</th>
                                    <th>Sku</th>
                                    <th>Product Name</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>Category</th>
                                    <th>Remove</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr><td>123</td>
                                    <td>TestSku</td>
                                    <td>Some productname</td>
                                    <td>$10,000.00</td>
                                    <td>12</td>
                                    <td>Category</td>
                                    <td><a class="delete" href="javascript:;">Delete</a></td>
                                </tr>
                                </tbody>
                            </table>
                        </div>



                        <div class="modal fade" id="acessoryModal" tabindex="-1" role="acessoryModal" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                        <h4 class="modal-title">Add Acessory Items</h4>
                                    </div>
                                    <div class="modal-body">
                                        Select 2 input (multi/ajax)
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn default" data-dismiss="modal">Close</button>
                                        Send Ajax Call to add on click<button type="button" class="btn blue">Save changes</button>
                                    </div>
                                </div>
                                <!-- /.modal-content -->
                            </div>
                            <!-- /.modal-dialog -->
                        </div>
                    </div>
                </div>
            </div>
         </div>


        <div class="col-md-6">
            <!-- Related products-->
            <div class="portlet box yellow">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-gift"></i>Cross Sells
                    </div>
                    <div class="tools">
                        <a href="javascript:;" class="collapse">
                        </a>

                    </div>
                </div>


                <div class="portlet-body">
                    <div class="row">
                        <div class="col-md-11">
                            <div class="table-toolbar">
                                <div class="btn-group">
                                    <a class="btn green" data-toggle="modal" href="#crossModal">
                                        Add Cross Sell <i class="fa fa-plus"></i></a>
                                </div>
                            </div>
                            <table class="table table-striped table-bordered table-hover" id="crossSellDisplay">
                                <thead>
                                <tr><th>id</th>
                                    <th>Sku</th>
                                    <th>Product Name</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>Category</th>
                                    <th>Remove</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr><td>123</td>
                                    <td>TestSku</td>
                                    <td>Some productname</td>
                                    <td>$10,000.00</td>
                                    <td>12</td>
                                    <td>Category</td>
                                    <td><a class="delete" href="javascript:;">Delete</a></td>
                                </tr>
                                </tbody>
                            </table>
                        </div>


                        <div class="modal fade" id="crossModal" tabindex="-1" role="crossModal" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                        <h4 class="modal-title">Add Cross Sell Items</h4>
                                    </div>
                                    <div class="modal-body">
                                        Select 2 input (multi/ajax)
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn default" data-dismiss="modal">Close</button>
                                        Send Ajax Call to add on click<button type="button" class="btn blue">Save changes</button>
                                    </div>
                                </div>
                                <!-- /.modal-content -->
                            </div>
                            <!-- /.modal-dialog -->
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>





</div>

<div class="tab-pane" id="tab_images">
<div class="row">
    <div class="col-md-12">
        <blockquote>
            <p style="font-size:16px">
                Add or Drag Files to Upload
            </p>
        </blockquote>
        <br>
        <form id="fileupload" action="/form/imagesave" method="POST" enctype="multipart/form-data">
            <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
            <div class="row fileupload-buttonbar">
                <div class="col-lg-7">
                    <!-- The fileinput-button span is used to style the file input field as button -->
								<span class="btn green fileinput-button">
								<i class="fa fa-plus"></i>
								<span>
								Add files... </span>
								<input type="file" name="files[]" multiple="">
								</span>
                    <button type="submit" class="btn blue start">
                        <i class="fa fa-upload"></i>
								<span>
								Start upload </span>
                    </button>
                    <button type="reset" class="btn warning cancel">
                        <i class="fa fa-ban-circle"></i>
								<span>
								Cancel upload </span>
                    <!--
                    </button>
                    <button type="button" class="btn red delete">
                        <i class="fa fa-trash"></i>
								<span>
								Delete </span>
                    </button>
                    <input type="checkbox" class="toggle">
                    -->
                    <!-- The global file processing state -->
								<span class="fileupload-process">
								</span>
                </div>
                <!-- The global progress information -->
                <div class="col-lg-5 fileupload-progress fade">
                    <!-- The global progress bar -->
                    <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                        <div class="progress-bar progress-bar-success" style="width:0%;">
                        </div>
                    </div>
                    <!-- The extended global progress information -->
                    <div class="progress-extended">
                        &nbsp;
                    </div>
                </div>
            </div>
            <!-- The table listing the files available for upload/download -->
            <table role="presentation" class="table table-striped clearfix">
                <tbody class="files">
                </tbody>
            </table>
        </form>

        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">Images</h3>
            </div>
            <div class="panel-body">




<!--Current Images-->
<form id="imageForm" method="POST">
<table id="currentImages" class="table table-bordered table-hover">
    <thead>
    <tr role="row" class="heading">
        <th width="8%">
            Image
        </th>
        <th width="25%">
            Label
        </th>
        <th width="8%">
            Sort Order
        </th>
        <th width="10%">
            Base Image
        </th>
        <th width="10%">
            Small Image
        </th>
        <th width="10%">
            Thumbnail
        </th>
        <th width="10%">
        </th>
    </tr>
    </thead>
    <tbody>

    <?php

    foreach($this->data->getImageGallery() as $image){
        echo '<tr><td><img class="img-responsive" src="http://www.focuscamera.com/media/catalog/product'.$image->getFilename().'" alt=""></td>';
        echo '<input type="hidden" name="imageGallery[][][filename]" value ="'.$image->getFilename().'">';
        echo '<td><input type="text" class="form-control" name="imageGallery[][][label]" value="'.$image->getLabel().'"></td>';
        echo '<td><input type="text" class="form-control" name="imageGallery[][][position]" value="'.$image->getPosition().'"></td>';
        echo '<td><label><input type="radio" name="imageGallery[][][thumbnail]" value="1"></label></td>
        <td><label><input type="radio" name="imageGallery[][][small_image]" value="1"></label></td>
        <td><label><input type="radio" name="imageGallery[][][image]" value="1"></label></td>
        <td><a href="javascript:;" class="imageremove btn default btn-sm"><i class="fa fa-times"></i> Remove </a></td></tr>';



    }

    ?>
    <!--<tr>
        <td>
            <a href="../../assets/admin/pages/media/works/img1.jpg" class="fancybox-button" data-rel="fancybox-button">
                <img class="img-responsive" src="../../assets/admin/pages/media/works/img1.jpg" alt="">
            </a>
        </td>
        <td>
            <input type="text" class="form-control" name="product[images][1][label]" value="Thumbnail image">
        </td>
        <td>
            <input type="text" class="form-control" name="product[images][1][sort_order]" value="1">
        </td>
        <td>
            <label>
                <input type="radio" name="product[images][1][image_type]" value="1">
            </label>
        </td>
        <td>
            <label>
                <input type="radio" name="product[images][1][image_type]" value="2">
            </label>
        </td>
        <td>
            <label>
                <input type="radio" name="product[images][1][image_type]" value="3" checked>
            </label>
        </td>
        <td>
            <a href="javascript:;" class="btn default btn-sm">
                <i class="fa fa-times"></i> Remove </a>
        </td>
    </tr>-->

    </tbody>
</table>
</form>


            </div>
        </div>

    </div>
</div>


</div>


<div class="tab-pane" id="tab_categories">
    <!-- categories -->
    <div class = "row">
    <div class = "col-md-4">

        <div class="portlet box green-meadow tabbable">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-gift"></i>Categories
                </div>
            </div>


            <div class="portlet-body">
                <div class="portlet-tabs">
                    <ul class="nav nav-tabs">
                        <li>
                            <a href="#portlet_inbox" data-toggle="tab">New aSavings</a>
                        </li>
                        <li>
                            <a href="#portlet_newfocus" data-toggle="tab">New Focus</a>
                        </li>
                        <li>
                            <a href="#portlet_asave" data-toggle="tab">aSavings</a>
                        </li>
                        <li  class="active">
                            <a href="#portlet_focus" data-toggle="tab">Focus</a>
                        </li>
                    </ul>
                    <div class="row">
                        <div class="tab-content">



                            <!-- Focus categories-->
                            <div class="tab-pane col-md-11 active" id="portlet_focus">
                                <h3>Focus Camera Categories</h3>
                                <div id="tree_2" class="tree-demo"></div>
                            </div>


                            <!-- aSave Categories-->
                            <div class="tab-pane col-md-11" id="portlet_asave">
                                <div class="form-body">
                                    <h3>aSavings Categories</h3>
                                    <div id="asave" class="tree-demo"></div>
                                </div>
                            </div>


                            <!-- newFocus categories-->
                            <div class="tab-pane col-md-11" id="portlet_newfocus">
                                <h3>Focus Camera Categories (New Site)</h3>
                                <div id="newfocus" class="tree-demo"></div>
                            </div>










                        </div><!--end tab content-->

                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class = "col-md-6">
        <div class="portlet box green-meadow">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-gift"></i>Attributes
                </div>
            </div>

            <div class="portlet-body">
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label class="control-label col-md-3">Color</label>
                            <div class="col-md-9">
                                <select class="form-control input-small" data-placeholder="Select Color">
                                    <option value="0">Black</option>
                                    <option value="1">Silver</option>
                                    <option value="2">Red</option>
                                    <option value="3">Pink</option>
                                    <option value="4">Blue</option>
                                    <option value="5">Green</option>
                                    <option value="6">Yellow</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="form-group">
                            <label class="control-label col-md-3">Packs</label>
                            <div class="col-md-9">
                                <select class="form-control input-small" data-placeholder="Select Pack">
                                    <option value="0">Two</option>
                                    <option value="1">Three</option>
                                    <option value="1">four</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="form-group">
                            <label class="control-label col-md-3">Capacity</label>
                            <div class="col-md-9">
                                <select class="form-control input-small" data-placeholder="Select Capaciaty">
                                    <option value="0">8 GB</option>
                                    <option value="1">16 GB</option>
                                    <option value="2">32 GB</option>
                                    <option value="3">64 GB</option>
                                    <option value="4">128 GB</option>
                                    <option value="5">256 GB</option>
                                </select>
                            </div>
                        </div>
                    </div>

                </div>

                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label class="control-label col-md-3">Network</label>
                            <div class="col-md-9">
                                <select class="form-control input-small" data-placeholder="Select Color">
                                    <option value="0">Black</option>
                                    <option value="1">Silver</option>
                                    <option value="2">Red</option>
                                    <option value="3">Pink</option>
                                    <option value="4">Blue</option>
                                    <option value="5">Green</option>
                                    <option value="6">Yellow</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="form-group">
                            <label class="control-label col-md-3">Size [Cloths]</label>
                            <div class="col-md-9">
                                <select class="form-control input-small" data-placeholder="Select Pack">
                                    <option value="0">Two</option>
                                    <option value="1">Three</option>
                                    <option value="1">four</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="form-group">
                            <label class="control-label col-md-3">Size (mm) [Sunglasses</label>
                            <div class="col-md-9">
                                <select class="form-control input-small" data-placeholder="Select Capaciaty">
                                    <option value="0">8 GB</option>
                                    <option value="1">16 GB</option>
                                    <option value="2">32 GB</option>
                                    <option value="3">64 GB</option>
                                    <option value="4">128 GB</option>
                                    <option value="5">256 GB</option>
                                </select>
                            </div>
                        </div>
                    </div>

                </div>

                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label class="control-label col-md-3">Resolution [camera]</label>
                            <div class="col-md-9">
                                <select class="form-control input-small" data-placeholder="Select Color">
                                    <option value="0">Black</option>
                                    <option value="1">Silver</option>
                                    <option value="2">Red</option>
                                    <option value="3">Pink</option>
                                    <option value="4">Blue</option>
                                    <option value="5">Green</option>
                                    <option value="6">Yellow</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="form-group">
                            <label class="control-label col-md-3">Sensor Size</label>
                            <div class="col-md-9">
                                <select class="form-control input-small" data-placeholder="Select Pack">
                                    <option value="0">Two</option>
                                    <option value="1">Three</option>
                                    <option value="1">four</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4" style = "display: none;">
                        <div class="form-group">
                            <label class="control-label col-md-3">Zoom/Prime [Lens]</label>
                            <div class="col-md-9">
                                <select class="form-control input-small" data-placeholder="Select Capaciaty">
                                    <option value="0">8 GB</option>
                                    <option value="1">16 GB</option>
                                    <option value="2">32 GB</option>
                                    <option value="3">64 GB</option>
                                    <option value="4">128 GB</option>
                                    <option value="5">256 GB</option>
                                </select>
                            </div>
                        </div>
                    </div>

                </div>






            </div>



        </div>









        </div>
        </div>

    </div>
    </div>
</div>

</div>




</div>
</div>
</div>



</div>
</div>


