<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
            Product Edit <small>edit product content</small>
        </h3>
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <i class="fa fa-home"></i>
                <a href="index.html">Home</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="#">Content</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="#">Product Edit</a>
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>
<!-- END PAGE HEADER-->
<!-- BEGIN PAGE CONTENT-->
<div class="row">
<div class="col-md-12">
<!--<form class="form-horizontal form-row-seperated" action="#">-->
<div class="portlet">
<div class="portlet-title">
    <div class="caption">
        <i class="fa fa-shopping-cart"></i>Product Title
    </div>
    <div class="actions btn-set">
        <button type="button" name="back" class="btn default"><i class="fa fa-angle-left"></i> Back</button>

        <button class="btn green"><i class="fa fa-check"></i> Save</button>
    </div>
</div>
<div class="portlet-body">
<div class="tabbable">
<ul class="nav nav-tabs">
    <li class="active">
        <a href="#tab_general" data-toggle="tab">
            General </a>
    </li>
    <li>
        <a href="#tab_acessories" data-toggle="tab">
            Acessories </a>
    </li>
    <li>
        <a href="#tab_images" data-toggle="tab">
            Images <span class="badge badge-success">
											3 </span></a>
    </li>
    <li>
        <a href="#tab_reviews" data-toggle="tab">
            Catagories
        </a>
    </li>
</ul>






<div class="tab-content no-space">
<div class="tab-pane active" id="tab_general">
<br /> <br />
<!-- General Tab info-->


<!-- Standard-->
<div class="portlet box blue">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>Standard
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse">
            </a>

        </div>
    </div>


    <div class="portlet-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3" for="general_sku">SKU</label>
                    <div class="col-md-9">
                        <input type="text" class="form-control" name="general_sku" placeholder="SKU" style="width:140px" required/>
                        <span class="help-block">This is inline help </span>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3" for="general_sku">Name</label>
                    <div class="col-md-9">
                        <input type="text" class="form-control"  name="name" placeholder="Name" required/>
                        <span class="help-block">This is inline help </span>
                    </div>
                </div>
            </div>

        </div>

        <br />
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3" for="general_sku">Inventory</label>
                    <div class="col-md-9">
                        <input type="text" class="form-control" name="inventory"  placeholder="Inventory" style="width:140px" required/>
                        <span class="help-block">This is inline help </span>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3" for="general_sku">URL Key</label>
                    <div class="col-md-9">
                        <input type="text" class="form-control" name="urlkey" placeholder="URL Key"  required/>
                        <span class="help-block">This is inline help </span>
                    </div>
                </div>
            </div>

        </div>

        <br />
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3">Status</label>
                    <div class="col-md-9">
                        <select class="form-control input-medium select2me" data-placeholder="Select...">
                            <option value=""></option>
                            <option value="AL">Alabama</option>
                            <option value="WY">Wyoming</option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3" for="general_sku">Manufacturer</label>
                    <div class="col-md-9">
                        <select class="form-control input-medium select2me" data-placeholder="Select...">
                            <option value=""></option>
                            <option value="AL">Alabama</option>
                            <option value="WY">Wyoming</option>
                        </select>
                    </div>
                </div>
            </div>

        </div>

        <br />
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3" for="general_sku">Visibility</label>
                    <div class="col-md-9">
                        <select class="form-control input-medium select2me" data-placeholder="Select...">
                            <option value=""></option>
                            <option value="AL">Alabama</option>
                            <option value="WY">Wyoming</option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3" for="general_sku">Condition</label>
                    <div class="col-md-9">
                        <select class="form-control input-medium select2me" data-placeholder="Select...">
                            <option value=""></option>
                            <option value="AL">Alabama</option>
                            <option value="WY">Wyoming</option>
                        </select>
                    </div>
                </div>
            </div>

        </div>

        <br />
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3" for="general_sku">Tax Class</label>
                    <div class="col-md-9">
                        <select class="form-control input-medium select2me" data-placeholder="Select...">
                            <option value=""></option>
                            <option value="AL">Alabama</option>
                            <option value="WY">Wyoming</option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3" for="general_sku">Stock Status</label>
                    <div class="col-md-9">
                        <select class="form-control input-medium select2me" data-placeholder="Select...">
                            <option value=""></option>
                            <option value="AL">Alabama</option>
                            <option value="WY">Wyoming</option>
                        </select>
                    </div>
                </div>
            </div>

        </div>




    </div>
</div>


<br /><br />
<!--------------------Pricing------------------->
<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>Pricing
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse">
            </a>

        </div>
    </div>


    <div class="portlet-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3" for="general_sku">Price</label>
                    <div class="col-md-9">
                        <input type="text" class="form-control" name="general_sku" placeholder="Price" style="width:140px" required/>
                        <span class="help-block"></span>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3" for="general_sku">Cost</label>
                    <div class="col-md-9">
                        <input type="text" class="form-control"  name="name" placeholder="Cost" style="width:140px" required/>
                        <span class="help-block"></span>
                    </div>
                </div>
            </div>

        </div>


        <br />
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3" for="general_sku">MSRP</label>
                    <div class="col-md-9">
                        <input type="text" class="form-control" name="inventory"  placeholder="Rebate" style="width:140px" required/>
                        <span class="help-block"></span>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3">Map Display</label>
                    <div class="col-md-4">
                        <select class="form-control input-medium select2me" data-placeholder="Select...">
                            <option value=""></option>
                            <option value="AL">Alabama</option>
                            <option value="WY">Wyoming</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>



        <br />
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3" for="general_sku">Rebate Price</label>
                    <div class="col-md-9">
                        <input type="text" class="form-control" name="inventory"  placeholder="Rebate" style="width:140px" required/>
                        <span class="help-block"></span>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3">Start Date -End Date (Rebate)</label>
                    <div class="col-md-4">
                        <div class="input-group" id="rebate">
                            <input type="text" class="form-control">
												<span class="input-group-btn">
												<button class="btn default date-range-toggle" type="button"><i class="fa fa-calendar"></i></button>
												</span>
                        </div>
                    </div>
                </div>
            </div>

        </div>

        <br />
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3" for="general_sku">Special Price</label>
                    <div class="col-md-9">
                        <input type="text" class="form-control" name="inventory"  placeholder="Special Price" style="width:140px" required/>
                        <span class="help-block"></span>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3">Start Date -End Date (Special Price)</label>
                    <div class="col-md-4">
                        <div class="input-group" id="special">
                            <input type="text" class="form-control">
												<span class="input-group-btn">
												<button class="btn default date-range-toggle" type="button"><i class="fa fa-calendar"></i></button>
												</span>
                        </div>
                    </div>
                </div>
            </div>

        </div>

        <br />
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3" for="general_sku">Mail in rebate</label>
                    <div class="col-md-9">
                        <input type="text" class="form-control" name="inventory"  placeholder="Mail in Rebate" style="width:140px" required/>
                        <span class="help-block"></span>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label col-md-3">Start Date -End Date (Mail in rebate)</label>
                    <div class="col-md-4">
                        <div class="input-group" id="mailin">
                            <input type="text" class="form-control">
												<span class="input-group-btn">
												<button class="btn default date-range-toggle" type="button"><i class="fa fa-calendar"></i></button>
												</span>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>
</div>

<!--------Shipping------>
<div class="portlet box blue">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>Shipping
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse">
            </a>

        </div>
    </div>


    <div class="portlet-body">
        <div class="row">
            <div class="col-md-11">
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label col-md-3" for="general_sku">Weight</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" name="general_sku" placeholder="Weight" style="width:140px" required/>
                            <span class="help-block"></span>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label col-md-3" for="general_sku">US Standard</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control"  name="name" placeholder="US Standard" style="width:140px" required/>
                            <span class="help-block"></span>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label col-md-3" for="general_sku">US Expedited</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control"  name="name" placeholder="US Expedited" style="width:140px"  required/>
                            <span class="help-block"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--end row-->


        <div class="row">
            <div class="col-md-11">
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label col-md-3" for="general_sku">US Two Day</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" name="general_sku" placeholder="US Two Day" style="width:140px" required/>
                            <span class="help-block"></span>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label col-md-3" for="general_sku">US One Day</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control"  name="name" placeholder="US One Day" style="width:140px"  required/>
                            <span class="help-block"></span>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label col-md-3" for="general_sku">Europe First Class</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control"  name="name" placeholder="Europe First Class" style="width:140px"  required/>
                            <span class="help-block"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--end row-->



        <div class="row">
            <div class="col-md-11">
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label col-md-3" for="general_sku">Europe Priority</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" name="general_sku" placeholder="Europe Priority" style="width:140px" required/>
                            <span class="help-block"></span>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label col-md-3" for="general_sku">Asia First Class</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control"  name="name" placeholder="Asia First Class" style="width:140px"  required/>
                            <span class="help-block"></span>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label col-md-3" for="general_sku">Asia Priority</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control"  name="name" placeholder="Asia Priority" style="width:140px"  required/>
                            <span class="help-block"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--end row-->


        <div class="row">
            <div class="col-md-11">
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label col-md-3" for="general_sku">Canada First Class</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" name="general_sku" placeholder="Canada First Class" style="width:140px" required/>
                            <span class="help-block"></span>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label col-md-3" for="general_sku">Canada Priority</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control"  name="name" placeholder="Canada Priority" style="width:140px" required/>
                            <span class="help-block"></span>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label col-md-3" for="general_sku">Outside US,EUR CA, Asia First Class</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control"  name="name" placeholder="Outside US,EUR CA, Asia First Class" style="width:140px" required/>
                            <span class="help-block"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--end row-->


        <div class="row">
            <div class="col-md-11">
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label col-md-3" for="general_sku">Outside US,EUR CA, Asia Priority</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" name="general_sku" placeholder="Outside US,EUR CA, Asia Priority" style="width:140px" required/>
                            <span class="help-block"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--end row-->




    </div>

</div>


<!---Description-->
<div class="portlet box green tabbable">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>Description
        </div>
    </div>


    <div class="portlet-body">
        <div class=" portlet-tabs">
            <ul class="nav nav-tabs">
                <li>
                    <a href="#portlet_includesfree" data-toggle="tab">
                        Includes Free </a>
                </li>
                <li>
                    <a href="#portlet_inbox" data-toggle="tab">
                        In Box </a>
                </li>
                <li class="">
                    <a href="#portlet_sDescription" data-toggle="tab">
                        Short Description </a>
                </li>
                <li>
                    <a href="#portlet_description" data-toggle="tab"> Description</a>
                </li>
                <li  class="active">
                    <a href="#portlet_searchterms" data-toggle="tab"> Search Terms</a>
                </li>
            </ul>
            <div class="tab-content">

                <!-- search terms-->
                <div class="tab-pane active" id="portlet_searchterms">
                    <div class="form-body">
                        <div class="form-group">
                            <label class="control-label col-md-3" for="searchTerms">Search Terms</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="searchTerms" placeholder="Search Terms" required/>
                            </div>
                        </div>

                    </div>
                </div>

                <!-- Description-->
                <div class="tab-pane" id="portlet_description">
                    Description:
                    <div class="form-body">
                        <div class="form-group">
                            <div class="col-md-10">
                                <textarea class="wysihtml5 form-control" rows="6"></textarea>
                            </div>
                        </div>

                    </div>
                </div>

                <!--Short Description-->
                <div class="tab-pane" id="portlet_sDescription">
                    Short Description:
                    <div class="form-body">
                        <div class="form-group">
                            <div class="col-md-10">
                                <textarea class="wysihtml5 form-control" rows="6"></textarea>
                            </div>
                        </div>

                    </div>
                </div>

                <!--In Box-->
                <div class="tab-pane" id="portlet_inbox">
                    In the Box:
                    <div class="form-body">
                        <div class="form-group">
                            <div class="col-md-10">
                                <textarea class="wysihtml5 form-control" rows="6"></textarea>
                            </div>
                        </div>

                    </div>
                </div>

                <!--Includes Free-->
                <div class="tab-pane" id="portlet_includesfree">
                    Includes Free:
                    <div class="form-body">
                        <div class="form-group">
                            <div class="col-md-10">
                                <textarea class="wysihtml5 form-control" rows="6"></textarea>
                            </div>
                        </div>

                    </div>
                </div>


            </div>
         </div>
     </div>
</div>





</div>

<div class="tab-pane" id="tab_acessories">
    <!-- Acessories-->

    <div class="row">
        <div class="col-md-6">
            <!-- Related products-->
            <div class="portlet box blue">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-gift"></i>Acessories
                    </div>
                    <div class="tools">
                        <a href="javascript:;" class="collapse">
                        </a>

                    </div>
                </div>


                <div class="portlet-body">
                    <div class="row">
                        <div class="col-md-11">
                            <div class="table-toolbar">
                                <div class="btn-group">
                                    <a class="btn green" data-toggle="modal" href="#acessoryModal">
                                        Add Acessory <i class="fa fa-plus"></i></a>
                                </div>
                             </div>
                            <table class="table table-striped table-bordered table-hover" id="acessoriesDisplay">
                                <thead>
                                <tr><th>id</th>
                                    <th>Sku</th>
                                    <th>Product Name</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>Category</th>
                                    <th>Remove</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr><td>123</td>
                                    <td>TestSku</td>
                                    <td>Some productname</td>
                                    <td>$10,000.00</td>
                                    <td>12</td>
                                    <td>Category</td>
                                    <td><a class="delete" href="javascript:;">Delete</a></td>
                                </tr>
                                    </tbody>
                            </table>
                        </div>



                        <div class="modal fade" id="acessoryModal" tabindex="-1" role="acessoryModal" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                        <h4 class="modal-title">Add Acessory Items</h4>
                                    </div>
                                    <div class="modal-body">
                                        Select 2 input (multi/ajax)
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn default" data-dismiss="modal">Close</button>
                                        Send Ajax Call to add on click<button type="button" class="btn blue">Save changes</button>
                                    </div>
                                </div>
                                <!-- /.modal-content -->
                            </div>
                            <!-- /.modal-dialog -->
                        </div>
                    </div>
                </div>
            </div>
         </div>


        <div class="col-md-6">
            <!-- Related products-->
            <div class="portlet box yellow">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-gift"></i>Cross Sells
                    </div>
                    <div class="tools">
                        <a href="javascript:;" class="collapse">
                        </a>

                    </div>
                </div>


                <div class="portlet-body">
                    <div class="row">
                        <div class="col-md-11">
                            <div class="table-toolbar">
                                <div class="btn-group">
                                    <a class="btn green" data-toggle="modal" href="#crossModal">
                                        Add Cross Sell <i class="fa fa-plus"></i></a>
                                </div>
                            </div>
                            <table class="table table-striped table-bordered table-hover" id="crossSellDisplay">
                                <thead>
                                <tr><th>id</th>
                                    <th>Sku</th>
                                    <th>Product Name</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>Category</th>
                                    <th>Remove</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr><td>123</td>
                                    <td>TestSku</td>
                                    <td>Some productname</td>
                                    <td>$10,000.00</td>
                                    <td>12</td>
                                    <td>Category</td>
                                    <td><a class="delete" href="javascript:;">Delete</a></td>
                                </tr>
                                </tbody>
                            </table>
                        </div>


                        <div class="modal fade" id="crossModal" tabindex="-1" role="crossModal" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                        <h4 class="modal-title">Add Cross Sell Items</h4>
                                    </div>
                                    <div class="modal-body">
                                        Select 2 input (multi/ajax)
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn default" data-dismiss="modal">Close</button>
                                        Send Ajax Call to add on click<button type="button" class="btn blue">Save changes</button>
                                    </div>
                                </div>
                                <!-- /.modal-content -->
                            </div>
                            <!-- /.modal-dialog -->
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>





</div>

<div class="tab-pane" id="tab_images">
<div class="row">
    <div class="col-md-12">
        <blockquote>
            <p style="font-size:16px">
                File Upload widget with multiple file selection, drag&amp;drop support, progress bars and preview images for jQuery.<br>
                Supports cross-domain, chunked and resumable file uploads and client-side image resizing.<br>
                Works with any server-side platform (PHP, Python, Ruby on Rails, Java, Node.js, Go etc.) that supports standard HTML form file uploads.
            </p>
        </blockquote>
        <br>
        <form id="fileupload" action="../../assets/global/plugins/jquery-file-upload/server/php/" method="POST" enctype="multipart/form-data">
            <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
            <div class="row fileupload-buttonbar">
                <div class="col-lg-7">
                    <!-- The fileinput-button span is used to style the file input field as button -->
								<span class="btn green fileinput-button">
								<i class="fa fa-plus"></i>
								<span>
								Add files... </span>
								<input type="file" name="files[]" multiple="">
								</span>
                    <button type="submit" class="btn blue start">
                        <i class="fa fa-upload"></i>
								<span>
								Start upload </span>
                    </button>
                    <button type="reset" class="btn warning cancel">
                        <i class="fa fa-ban-circle"></i>
								<span>
								Cancel upload </span>
                    </button>
                    <button type="button" class="btn red delete">
                        <i class="fa fa-trash"></i>
								<span>
								Delete </span>
                    </button>
                    <input type="checkbox" class="toggle">
                    <!-- The global file processing state -->
								<span class="fileupload-process">
								</span>
                </div>
                <!-- The global progress information -->
                <div class="col-lg-5 fileupload-progress fade">
                    <!-- The global progress bar -->
                    <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                        <div class="progress-bar progress-bar-success" style="width:0%;">
                        </div>
                    </div>
                    <!-- The extended global progress information -->
                    <div class="progress-extended">
                        &nbsp;
                    </div>
                </div>
            </div>
            <!-- The table listing the files available for upload/download -->
            <table role="presentation" class="table table-striped clearfix">
                <tbody class="files">
                </tbody>
            </table>
        </form>
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">Demo Notes</h3>
            </div>
            <div class="panel-body">
                <ul>
                    <li>
                        The maximum file size for uploads in this demo is <strong>5 MB</strong> (default file size is unlimited).
                    </li>
                    <li>
                        Only image files (<strong>JPG, GIF, PNG</strong>) are allowed in this demo (by default there is no file type restriction).
                    </li>
                    <li>
                        Uploaded files will be deleted automatically after <strong>5 minutes</strong> (demo setting).
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<!--
<table class="table table-bordered table-hover">
    <thead>
    <tr role="row" class="heading">
        <th width="8%">
            Image
        </th>
        <th width="25%">
            Label
        </th>
        <th width="8%">
            Sort Order
        </th>
        <th width="10%">
            Base Image
        </th>
        <th width="10%">
            Small Image
        </th>
        <th width="10%">
            Thumbnail
        </th>
        <th width="10%">
        </th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            <a href="../../assets/admin/pages/media/works/img1.jpg" class="fancybox-button" data-rel="fancybox-button">
                <img class="img-responsive" src="../../assets/admin/pages/media/works/img1.jpg" alt="">
            </a>
        </td>
        <td>
            <input type="text" class="form-control" name="product[images][1][label]" value="Thumbnail image">
        </td>
        <td>
            <input type="text" class="form-control" name="product[images][1][sort_order]" value="1">
        </td>
        <td>
            <label>
                <input type="radio" name="product[images][1][image_type]" value="1">
            </label>
        </td>
        <td>
            <label>
                <input type="radio" name="product[images][1][image_type]" value="2">
            </label>
        </td>
        <td>
            <label>
                <input type="radio" name="product[images][1][image_type]" value="3" checked>
            </label>
        </td>
        <td>
            <a href="javascript:;" class="btn default btn-sm">
                <i class="fa fa-times"></i> Remove </a>
        </td>
    </tr>
    <tr>
        <td>
            <a href="../../assets/admin/pages/media/works/img2.jpg" class="fancybox-button" data-rel="fancybox-button">
                <img class="img-responsive" src="../../assets/admin/pages/media/works/img2.jpg" alt="">
            </a>
        </td>
        <td>
            <input type="text" class="form-control" name="product[images][2][label]" value="Product image #1">
        </td>
        <td>
            <input type="text" class="form-control" name="product[images][2][sort_order]" value="1">
        </td>
        <td>
            <label>
                <input type="radio" name="product[images][2][image_type]" value="1">
            </label>
        </td>
        <td>
            <label>
                <input type="radio" name="product[images][2][image_type]" value="2" checked>
            </label>
        </td>
        <td>
            <label>
                <input type="radio" name="product[images][2][image_type]" value="3">
            </label>
        </td>
        <td>
            <a href="javascript:;" class="btn default btn-sm">
                <i class="fa fa-times"></i> Remove </a>
        </td>
    </tr>
    <tr>
        <td>
            <a href="../../assets/admin/pages/media/works/img3.jpg" class="fancybox-button" data-rel="fancybox-button">
                <img class="img-responsive" src="../../assets/admin/pages/media/works/img3.jpg" alt="">
            </a>
        </td>
        <td>
            <input type="text" class="form-control" name="product[images][3][label]" value="Product image #2">
        </td>
        <td>
            <input type="text" class="form-control" name="product[images][3][sort_order]" value="1">
        </td>
        <td>
            <label>
                <input type="radio" name="product[images][3][image_type]" value="1" checked>
            </label>
        </td>
        <td>
            <label>
                <input type="radio" name="product[images][3][image_type]" value="2">
            </label>
        </td>
        <td>
            <label>
                <input type="radio" name="product[images][3][image_type]" value="3">
            </label>
        </td>
        <td>
            <a href="javascript:;" class="btn default btn-sm">
                <i class="fa fa-times"></i> Remove </a>
        </td>
    </tr>
    </tbody>
</table>
-->
</div>


<div class="tab-pane" id="tab_categories">
    <!-- categories -->
</div>

</div>




</div>
</div>
</div>



</div>
</div>


