<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
            Deals Search <small>Search For Deals</small>
        </h3>
        <ul class="page-breadcrumb breadcrumb">
            <li class="btn-group">
            </li>
            <li>
                <i class="fa fa-home"></i>
                <a href="/">Home</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="/">Marketing</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="/content/search">Deals Search</a>
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>
<!-- END PAGE HEADER-->


<!-- BEGIN PAGE CONTENT-->


<br /><br /><br />
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet box grey-cascade">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-globe"></i>Deals Search
                </div>
                <div class="tools">
                    <a href="javascript:;" class="collapse">
                    </a>
                    <a href="#portlet-config" data-toggle="modal" class="config">
                    </a>
                    <a href="javascript:;" class="reload">
                    </a>
                    <a href="javascript:;" class="remove">
                    </a>
                </div>
            </div>
            <div class="portlet-body">
                <div class="table-toolbar">
                    <div class="btn-group">
                    </div>
                </div>
                <table class="table table-striped table-bordered table-hover" id="searchDeals">
                    <thead>
                    <tr>
                        <th>Sku</th>
                        <th>Special Price</th>
                        <th>Inventory</th>
                        <th>Start Date</th>
                        <th>End Date</th>
                        <th>Max Quantity in Shopping Cart</th>
                        <th>Shipping</th>
                        <th>Remove</th>
                    </tr>

                    </thead>

                    <tbody>


                    </tbody>
                </table>
            </div>
        </div>
        <!-- END EXAMPLE TABLE PORTLET-->
    </div>
</div>





