<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
Website Assignment <small></small>
        </h3>
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <i class="fa fa-home"></i>
                <a href="/">Home</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="">Website Assignment</a>
                <i class="fa fa-angle-right"></i>
            </li>
<!--            <li>-->
<!--                <a href="">Product Edit</a>-->
<!--            </li>-->
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>
<!-- END PAGE HEADER-->
<!-- BEGIN PAGE CONTENT-->
<div class="row">

<!--<div class="col-md-12">-->
<!--    <div class="portlet">-->
<!--        <div class="portlet-title">-->
<!--        </div>-->
    <div class="portlet-body">



        <br /> <br />
            <div class="portlet box blue">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-gift"></i>Website Assignment
</div>
                    <div class="tools">
                        <a href="javascript:;" class="collapse">
                        </a>

                    </div>
                </div>
                <div class="portlet-body">
                    <div class="row">
                        <div class="col-md-12">
                             <table class="table table-striped table-bordered table-hover" id="websiteAssignment">
                                <thead>
                                <tr>
                                    <th>Manufacturer</th>
                                    <th>Site</th>
                                    <th>Date Assigned</th>
                                    <th>Edit</th>
                                </tr>
                                </thead>
                                <tbody>
                                    <tr>

                                                                            <td>3 legged beast</td>
                                                                            <td>Focus</td>
                                                                            <td>today</td>
                                                                            <td>Edit</td>
                                        <!--                                    <td></td>-->
                                        <!--                                    <td></td>-->
                                        <!--                                    <td><a class="delete" href="javascript:;">Delete</a></td>-->
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>



    </div>

</div>



</div>

</div>
</div>
</div>

</div>




</div>
</div>
</div>



</div>
</div>


