<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
Website Assignment <small></small>
        </h3>
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <i class="fa fa-home"></i>
                <a href="/">Home</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="">Website Assignment</a>
                <i class="fa fa-angle-right"></i>
            </li>

        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>
<!-- END PAGE HEADER-->
<!-- BEGIN PAGE CONTENT-->
<div class="row">

    <div class="portlet-body">



        <br /> <br />
            <div class="portlet box blue">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-gift"></i>Website Assignment
</div>
                    <div class="tools">
                        <a href="javascript:;" class="collapse">
                        </a>

                    </div>
                </div>
                <div class="portlet-body">
                    <div class="row">
                        <div class="col-md-12">
                             <table class="table table-striped table-bordered table-hover" id="webassignmenttable">
                                <thead>
                                <tr>
                                    <th>Manufacturer</th>
                                    <th>Site</th>
                                    <th>Date Assigned</th>
                                    <th>Changed By</th>
                                    <th>Edit</th>
                                </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                    <td>3 legged beast</td>
                                    <td>Focus</td>
                                    <td>today</td>
                                    <td>me</td>
                                    <td><a class="btn green mfcedit" data-toggle="modal" href="#crossModal">
                                            Edit <i class="fa fa-plus"></i></a></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>



                        <div class="modal fade" id="crossModal" tabindex="-1" role="crossModal" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                        <h4 class="modal-title">Edit Website Assignment</h4>
                                    </div>
                                    <div class="modal-body">


                                        <div class="row">
                                            <div class="col-md-11">
                                                <form id="websiteassignmentform">
                                                <div class="col-md-5">
                                                    Manufacturer:
                                                    <br />

                                                <label id="mfcLabel"></label>
                                                    <input type="hidden" id="mfcInput" name="mfc" value = "">

                                                </div>

                                                <div class="col-md-5">
                                                Select Website:
                                                <select id="webID" name="website" class="form-control input-small" data-placeholder="Select Website">
                                                    <option value="0">aSavings</option>
                                                    <option value="1">Focus</option>
                                                    <option value="2">Focus / aSavings</option>
                                                </select>
                                                </div>

                                            </div>
                                        </div>



                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn default" data-dismiss="modal">Close</button>
                                        <input type="submit" class="btn blue" value="Save Changes">
                                        </form>
                                    </div>
                                </div>
                                <!-- /.modal-content -->
                            </div>
                            <!-- /.modal-dialog -->
                        </div>



                    </div>
                </div>
            </div>



    </div>

</div>



</div>

</div>
</div>
</div>

</div>




</div>
</div>
</div>



</div>
</div>


