<?php
/**
* Configuration file generated by ZFTool
* The previous configuration file is stored in module.config.old
*
* @see https://github.com/zendframework/ZFTool
*/
return array(
    'router' => array(
        'routes' => array(
            'auth' => array(
                'type' => 'Zend\Mvc\Router\Http\Literal',
                'options' => array(
                    'route'    => '/login',
                    'defaults' => array(
                        'controller' => 'Authenticate\Controller\Authenticate',
                        'action'     => 'login',
                    ),
                ),
            ),
        ),
    ),

    'controllers' => array('invokables' => array('Authenticate\Controller\Authenticate' => 'Authenticate\Controller\AuthenticateController')),
    
    'view_manager' => array('template_path_stack' => array(__DIR__ . '/../view')),
    
    'di' => array(
        'services' => array(
            'Authenticate\Model\AuthTable' => 'Authenticate\Model\AuthTable'))
    );
