<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
            SKU History <small></small>
        </h3>
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <i class="fa fa-home"></i>
                <a href="/">Home</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="/search">SKU History</a>
                <i class="fa fa-angle-right"></i>
            </li>
<!--            <li>-->
<!--                <a href="">Product Edit</a>-->
<!--            </li>-->
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>
<!-- END PAGE HEADER-->
<!-- BEGIN PAGE CONTENT-->
<div class="row">
    <form id="generalForm" action="/form" method="POST">
<!--<div class="col-md-12">-->
<!--    <div class="portlet">-->
<!--        <div class="portlet-title">-->
<!--        </div>-->
    <div class="portlet-body">
        <div class="tabbable">
            <div class="tab-content no-space">
                <div class="tab-pane active" id="tab_general">
                    <br /> <br />
                        <div class="portlet box blue">
                            <div class="portlet-title">
                                <div class="caption">
                                    <i class="fa fa-gift"></i>SKU History
                                </div>
                                <div class="tools">
                                    <a href="javascript:;" class="collapse">
                                    </a>

                                </div>
                            </div>
                            <div class="portlet-body">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="row">

                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="control-label col-md-3">Start Date-End Date</label>
                                                    <div class="col-md-5">
                                                        <div class="input-group" id="filterDateRange defaultrange">
                                                            <input type="text" class="form-control" name="filterDateRange" id="filterDateRange" >
                                                            <span class="input-group-btn">
                                                                <button id="btnDateRange" class="btn default date-range-toggle" type="button"><i class="fa fa-calendar"></i></button>
                                                            </span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-4">
                                                <label class="control-label col-md-4">Filter by User</label>
                                                <div class="col-md-4">
                                                    <input type="search" name="findUser" />
                                                </div>
                                            </div>
                                        </div>
                                         <table class="table table-striped table-bordered table-hover" id="skuHistoryDisplay">
                                            <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>Old Value</th>
                                                <th>New Value</th>
                                                <th>Changed By</th>
                                                <th>Date Changed</th>
                                                <th>Property</th>
                                                <th>Revert</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                                <tr class="accessory-data">
                                                    <!--                                    <td></td>-->
                                                    <!--                                    <td></td>-->
                                                    <!--                                    <td></td>-->
                                                    <!--                                    <td></td>-->
                                                    <!--                                    <td></td>-->
                                                    <!--                                    <td></td>-->
                                                    <!--                                    <td><a class="delete" href="javascript:;">Delete</a></td>-->
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>
    </form>
</div>



</div>

</div>
</div>
</div>

</div>




</div>
</div>
</div>



</div>
</div>


