<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
            Help Desk <small>Kanban Board</small>
        </h3>
        <ul class="page-breadcrumb breadcrumb">
            <li class="btn-group">
                <!--
                <button type="button" class="btn blue dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true">
                    <span>Actions</span><i class="fa fa-angle-down"></i>
                </button>
                <ul class="dropdown-menu pull-right" role="menu">
                    <li>
                        <a href="#">Action</a>
                    </li>
                    <li>
                        <a href="#">Another action</a>
                    </li>
                    <li>
                        <a href="#">Something else here</a>
                    </li>
                    <li class="divider">
                    </li>
                    <li>
                        <a href="#">Separated link</a>
                    </li>
                </ul>
                -->
            </li>
            <li>
                <i class="fa fa-home"></i>
                <a href="/">Home</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="#">Help Desk</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="/helpdesk/kanban">Kanban</a>
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>
<!-- END PAGE HEADER-->








<div class="row" id="sortable_portlets">
    <div class="col-md-3 column sortable">
        <h1>Backlog</h1>


        <div class=" portlet box red">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-gift"></i>Add Kanban Board to Spex
                </div>
                <div class="tools">
                    <a href="javascript:;" class="expand">
                </div>
                <div class="actions">
                    <a href="#" class="btn btn-default btn-sm">
                        <i class="fa fa-pencil"></i> Edit </a>
                    <div class="btn-group">
                        <a class="btn btn-sm btn-default" href="#" data-toggle="dropdown">
                            <i class="fa fa-user"></i> User <i class="fa fa-angle-down"></i>
                        </a>
                        <ul class="dropdown-menu pull-right">
                            <li>
                                <a href="#">
                                    <i class="fa fa-pencil"></i> Edit </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="fa fa-trash-o"></i> Delete </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="fa fa-ban"></i> Ban </a>
                            </li>
                            <li class="divider">
                            </li>
                            <li>
                                <a href="#">
                                    <i class="i"></i> Make admin </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="portlet-body">
                <table>
                    <tr><td>Estimate:</td><td>5</td></tr>
                    <tr><td>Date Opened:</td><td>12/24/2014</td></tr>
                    <tr><td>Details:</td><td>This is a ticket</td></tr>
                </table>
            </div>
        </div>
    </div>

    <div class="col-md-3 column sortable">
        <h1>In Progress</h1>
        <!-- BEGIN Portlet PORTLET-->
        <div class=" portlet box red">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-gift"></i>Add rules for gift..
                </div>
                <div class="tools">
                    <a href="javascript:;" class="expand">
                </div>
                <div class="actions">
                    <a href="#" class="btn btn-default btn-sm">
                        <i class="fa fa-pencil"></i> Edit </a>
                    <div class="btn-group">
                        <a class="btn btn-sm btn-default" href="#" data-toggle="dropdown">
                            <i class="fa fa-user"></i> User <i class="fa fa-angle-down"></i>
                        </a>
                        <ul class="dropdown-menu pull-right">
                            <li>
                                <a href="#">
                                    <i class="fa fa-pencil"></i> Edit </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="fa fa-trash-o"></i> Delete </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="fa fa-ban"></i> Ban </a>
                            </li>
                            <li class="divider">
                            </li>
                            <li>
                                <a href="#">
                                    <i class="i"></i> Make admin </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="portlet-body">
                <h4>Add rules for giftcard use</h4>
                <table>
                    <tr><td>Estimate:</td><td>5</td></tr>
                    <tr><td>Date Opened:</td><td>12/24/2014</td></tr>
                    <tr><td>Details:</td><td>This is a ticket</td></tr>
                </table>
            </div>
        </div>
        <!-- END Portlet PORTLET-->
    </div>

    <div class="col-md-3 column sortable" style="margin-bottom:20px; height:100px;">
            <h1>On Hold</h1>

        <div class=" portlet box red">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-gift"></i>Add Kanban Board to
                </div>
                <div class="tools">
                    <a href="javascript:;" class="expand">
                </div>
                <div class="actions">
                    <a href="#" class="btn btn-default btn-sm">
                        <i class="fa fa-pencil"></i> Edit </a>
                    <div class="btn-group">
                        <a class="btn btn-sm btn-default" href="#" data-toggle="dropdown">
                            <i class="fa fa-user"></i> User <i class="fa fa-angle-down"></i>
                        </a>
                        <ul class="dropdown-menu pull-right">
                            <li>
                                <a href="#">
                                    <i class="fa fa-pencil"></i> Edit </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="fa fa-trash-o"></i> Delete </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="fa fa-ban"></i> Ban </a>
                            </li>
                            <li class="divider">
                            </li>
                            <li>
                                <a href="#">
                                    <i class="i"></i> Make admin </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="portlet-body">
                <table>
                    <tr><td>Estimate:</td><td>5</td></tr>
                    <tr><td>Date Opened:</td><td>12/24/2014</td></tr>
                    <tr><td>Details:</td><td>This is a ticket</td></tr>
                </table>
            </div>
        </div>
    </div>


    <div class="col-md-3 column sortable" style="margin-bottom:20px; height:100px;">
        <h1>Completed</h1>

        <div class=" portlet box red">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-gift"></i>Add logos
                </div>
                <div class="tools">
                    <a href="javascript:;" class="expand">
                </div>
                <div class="actions">
                    <a href="#" class="btn btn-default btn-sm">
                        <i class="fa fa-pencil"></i> Edit </a>
                    <div class="btn-group">
                        <a class="btn btn-sm btn-default" href="#" data-toggle="dropdown">
                            <i class="fa fa-user"></i> User <i class="fa fa-angle-down"></i>
                        </a>
                        <ul class="dropdown-menu pull-right">
                            <li>
                                <a href="#">
                                    <i class="fa fa-pencil"></i> Edit </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="fa fa-trash-o"></i> Delete </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="fa fa-ban"></i> Ban </a>
                            </li>
                            <li class="divider">
                            </li>
                            <li>
                                <a href="#">
                                    <i class="i"></i> Make admin </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="portlet-body">
                <table>
                    <tr><td>Estimate:</td><td>5</td></tr>
                    <tr><td>Date Opened:</td><td>12/24/2014</td></tr>
                    <tr><td>Details:</td><td>This is a ticket</td></tr>
                </table>
            </div>
        </div>
    </div>
</div>
