<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */



define('CONFIG_DIR', dirname(__DIR__) . '/config');
define('MODULE_DIR', dirname(__DIR__) . '/module');

return array(
    'modules' => array(
        'ZendDeveloperTools',
//        'DoctrineModule',
//        'DoctrineORMModule',
        'Authenticate',
        'Common',
        'Content',
        'Users',
        'Api',
        'Logging',
        'Helpdesk',
        ),
    'module_listener_options' => array(
        'config_glob_paths' => array('config/autoload/{,*.}{global,local}.php'),
        'module_paths' => array(
            './module',
            './vendor'
            )
        )
    );
