<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
            API Feeds
        </h3>
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <i class="fa fa-home"></i>
                <a href="/">Home</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="#">API Feeds</a>
                <i class="fa fa-angle-right"></i>
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>
<div class="portlet box blue">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>Magento
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse">
            </a>
        </div>
    </div>


    <div class="portlet-body">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 margin-bottom-10">
                <div class="dashboard-stat blue-madison">
                    <div class="visual">
                        <i class="fa fa-briefcase fa-icon-medium"></i>
                    </div>
                    <div class="details">
                        <div class="number" id="mage-update">
<!--                            --><?php //$this->dirtyCount;?>
                        </div>
                        <div class="desc">
                            Items Requiring Update
                        </div>
                    </div>
                    <a class="more show-updates" href="">
                        Show Updates<i class="m-icon-swapright m-icon-white"></i>
                    </a>
                </div>
            </div>

<!--            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">-->
<!--                <div class="dashboard-stat green-haze">-->
<!--                    <div class="visual">-->
<!--                        <i class="fa fa-shopping-cart"></i>-->
<!--                    </div>-->
<!--                    <div class="details">-->
<!--                        <div class="number">-->
                                <?php //$this->cleanCount?>
<!--                        </div>-->
<!--                        <div class="desc">-->
<!--                            Synced-->
<!--                        </div>-->
<!--                    </div>-->
<!--                    <a class="more" href="#">-->
<!--                        &nbsp;<i class="m-icon-swapright m-icon-white"></i>-->
<!--                    </a>-->
<!--                </div>-->
<!--            </div>-->
            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                <div class="dashboard-stat green-haze">
                    <div class="visual">
                        <i class="fa fa-shopping-cart"></i>
                    </div>
                    <div class="details">
                        <div class="number" id="mage-image">
<!--                            --><?php //$this->newImages?>
                        </div>
                        <div class="desc">
                            New Images
                        </div>
                    </div>
                    <a class="more show-images" href="">
                        Show Images<i class="m-icon-swapright m-icon-white"></i>
                    </a>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                <div class="dashboard-stat red-intense">
                    <div class="visual">
                        <i class="fa fa-group fa-icon-medium"></i>
                    </div>
                    <div class="details">
                        <div class="number" id="mage-new-products">
<!--                            --><?php //$this->newCount?>
                        </div>
                        <div class="desc">
                            Newly Created
                        </div>
                    </div>
                    <a class="more new-items" href="">
                        Show New Items <i class="m-icon-swapright m-icon-white"></i>
                    </a>
                </div>
            </div>
        </div>
        <?php
//            $flash = $this->flashMessenger();
//            $flash->setMessageOpenFormat('<div%s>
//                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
//                        &times;
//                    </button>
//                    <ul><li class="error_message">')
//                ->setMessageSeparatorString('')
//                ->setMessageCloseString('</li></ul></div>');
//            echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
//            echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
//            echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning', 'alert-warn-message'));
//            echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
        ?>


        <div class="row magento-updates">
                    <div class="col-md-4 pushItems">
<!--                        <div id="spinner1">-->
<!--                            <img src="/assets/admin/layout/img/spinner-blue.gif" class="hidden" id="spinblue">-->
<!--                        </div>-->
                        <form id="mageForm" action="/api-feeds/magento/items" method="post">
                            <button class="btn blue btn-block btn-lg m-icon-big pushItemsBtn" >
                                <!--                                href="/api-feeds/magento/items"-->
                                Push Items <i class="m-icon-big-swapright m-icon-white"></i>
                            </button>
                        </form>
                    </div>
                </div>
                <div class="row magento-images">
                    <div class="col-md-4">
                    </div>
                    <div class="col-md-4 ">
<!--                        <div id="spinner2">-->
<!--                            <img src="/assets/admin/layout/img/spinner-green.gif" class="hidden" id="spingreen">-->
<!--                        </div>-->
                        <form id="mageImages" action="/api-feeds/magento/new-images" method="post">
                            <button href="/api-feeds/magnto/images" class="btn green btn-block btn-lg m-icon-big pushImagesBtn">
                                Push Images <i class="m-icon-big-swapright m-icon-white"></i>
                            </button>
<!--                            <div class="skuimg">-->
<!--                            </div>-->
                        </form>
                    </div>
                </div>
                <div class="row magento-new-items">
                    <div class="col-md-4">
                    </div>
                    <div class="col-md-4">
                    </div>
                    <div class="col-md-4 ">
                        <div id="spinner3" style="display: none; z-index: 1000; background-color: silver; opacity: .5; position: absolute; height: 500px; width: 500px;">
                            <img src="/assets/admin/layout/img/spinner-red.gif">
                        </div>
                        <form id="mageNewProds" action="/api-feeds/magento/new-items" method="post">
                            <button href="/api-feeds/magento/new-items" class="btn red btn-block btn-lg m-icon-big pushNewProducts">
                                Push New Items <i class="m-icon-big-swapright m-icon-white"></i>
                            </button>
                        </form>
                    </div>
                </div>
                <br /><br />
                <div class="row" id="soapUpdates">
                    <div class="col-md-12">
                        <div class="portlet box blue">
                            <div class="portlet-title">
                                <div class="caption">
                                    <i class="fa fa-gift"></i>Update Items
                                </div>
                                <div class="tools">
                                    <a href="javascript:;" class="collapse">
                                    </a>
                                </div>
                            </div>
                            <div class="portlet-body">
                                <table class="table table-striped table-bordered table-hover" id="kpiUpdates">
                                    <thead>

                                    <tr>
                                        <th><input type="checkbox" id="skuItems" name="skuItem[]" value="" /></th>
<!--                                        <th>ID</th>-->
                                        <th>ID</th>
                                        <th>Sku</th>
                                        <th>Attribute Field</th>
                                        <th>Attribute Field</th>
                                        <th>New Attribute Value</th>
                                        <th>Last Modified Date</th>
                                        <th>Changed By</th>
                                    </tr>
                                    </thead>
                                </table>
                            </div>
                        </div>
                        <div class="portlet box blue">
                            <div class="portlet-title">
                                <div class="caption">
                                    <i class="fa fa-gift"></i>Update Categories
                                </div>
                                <div class="tools">
                                    <a href="javascript:;" class="collapse">
                                    </a>
                                </div>
                            </div>
                            <div class="portlet-body">
                                <table class="table table-striped table-bordered table-hover" id="kpiCategories">
                                    <thead>
                                    <tr>
                                        <th><input type="checkbox" id="skuCategories" name="skuCategories[]" value="" /></th>
                                        <th>SKU</th>
                                        <th>Entity ID</th>
                                        <th>catid</th>
                                        <th>Category</th>
                                        <th>DataState</th>
                                        <th>Status</th>
                                        <th>Changed By</th>
                                    </tr>
                                    </thead>
                                </table>
                            </div>
                        </div>
                        <div class="portlet box blue">
                            <div class="portlet-title">
                                <div class="caption">
                                    <i class="fa fa-gift"></i>Update Related Products
                                </div>
                                <div class="tools">
                                    <a href="javascript:;" class="collapse">
                                    </a>
                                </div>
                            </div>
                            <div class="portlet-body">
                                <table class="table table-striped table-bordered table-hover" id="kpiRelatedProducts">
                                    <thead>
        <!--                            <div class="desc">-->
        <!--                                <h3>Update Related Products</h3>-->
        <!--                            </div>-->
                                    <tr>
                                        <th><input type="checkbox" id="skuLinks" name="skuLinks[]" value="" /></th>
                                        <th>ID</th>
                                        <th>SKU</th>
                                        <th>LinkedID</th>
                                        <th>Linked SKU</th>
                                        <th>DataState</th>
                                        <th>State</th>
                                        <th>Type</th>
                                        <th>Changed By</th>
                                    </tr>
                                    </thead>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row" id="soapImages">
                    <div class="col-md-12">
                        <div class="portlet box green">
                            <div class="portlet-title">
                                <div class="caption">
                                    <i class="fa fa-gift"></i>New Images
                                </div>
                                <div class="tools">
                                    <a href="javascript:;" class="collapse">
                                    </a>
                                </div>
                            </div>
                            <div class="portlet-body">
                                <table class="table table-striped table-bordered table-hover" id="kpiImages">
                                    <thead>
                                    <tr>
                                        <th><input type="checkbox" id="skuImages" name="skuImages[]" value="" /></th>
                                        <th>ID</th>
                                        <th>Position</th>
                                        <th>ID</th>
                                        <th>Sku</th>
                                        <th>Label</th>
                                        <th>Image</th>
                                        <th>Date Created</th>
                                        <th>Created By</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row" id="soapNewProducts">
                    <div class="col-md-12">
                        <div class="portlet box red">
                            <div class="portlet-title">
                                <div class="caption">
                                    <i class="fa fa-gift"></i>New Products
                                </div>
                                <div class="tools">
                                    <a href="javascript:;" class="collapse">
                                    </a>
                                </div>
                            </div>
                            <div class="portlet-body">
                                <table class="table table-striped table-bordered table-hover" id="kpiNewProducts">
                                    <thead>
                                    <tr>
<!--                                        <th>></th>-->
                                        <th><input type="checkbox" id="skuNewProducts" name="skuNewProducts[]" value="" /></th>
                                        <th>ID</th>
<!--                                        <th>Website</th>-->
                                        <th>Sku</th>
<!--                                        <th>Attribute</th>-->
<!--                                        <th>Attribute Value</th>-->
                                        <th>Date Created</th>
                                        <th>Created By</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
    </div>
</div>