<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
            API Feeds
        </h3>
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <i class="fa fa-home"></i>
                <a href="/">Home</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="#">API Feeds</a>
                <i class="fa fa-angle-right"></i>
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>
<div class="portlet box blue">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>Magento
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse">
            </a>
        </div>
    </div>


    <div class="portlet-body">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 margin-bottom-10">
                <div class="dashboard-stat blue-madison">
                    <div class="visual">
                        <i class="fa fa-briefcase fa-icon-medium"></i>
                    </div>
                    <div class="details">
                        <div class="number">
                            <?=$this->dirtyCount;//sku['dirty']?>
                        </div>
                        <div class="desc">
                            Items Requiring Update
                        </div>
                    </div>
                    <a class="more show-updates" href="">
                        Show Updates<i class="m-icon-swapright m-icon-white"></i>
                    </a>
                </div>
            </div>

<!--            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">-->
<!--                <div class="dashboard-stat green-haze">-->
<!--                    <div class="visual">-->
<!--                        <i class="fa fa-shopping-cart"></i>-->
<!--                    </div>-->
<!--                    <div class="details">-->
<!--                        <div class="number">-->
                                <?php //$this->cleanCount?>
<!--                        </div>-->
<!--                        <div class="desc">-->
<!--                            Synced-->
<!--                        </div>-->
<!--                    </div>-->
<!--                    <a class="more" href="#">-->
<!--                        &nbsp;<i class="m-icon-swapright m-icon-white"></i>-->
<!--                    </a>-->
<!--                </div>-->
<!--            </div>-->
            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                <div class="dashboard-stat green-haze">
                    <div class="visual">
                        <i class="fa fa-shopping-cart"></i>
                    </div>
                    <div class="details">
                        <div class="number">
                            <?=$this->newImages?>
                        </div>
                        <div class="desc">
                            New Images
                        </div>
                    </div>
                    <a class="more show-images" href="">
                        Show Images<i class="m-icon-swapright m-icon-white"></i>
                    </a>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                <div class="dashboard-stat red-intense">
                    <div class="visual">
                        <i class="fa fa-group fa-icon-medium"></i>
                    </div>
                    <div class="details">
                        <div class="number">
<!--                            --><?php //=$this->newCount?>
                        </div>
                        <div class="desc">
                            Newly Created
                        </div>
                    </div>
                    <a class="more" href="/search">
                        Show New Items <i class="m-icon-swapright m-icon-white"></i>
                    </a>
                </div>
            </div>
        </div>

                <div class="row magento-updates">
                    <div class="col-md-4">
                        <a href="/api-feeds/magento/items" class="btn blue btn-block btn-lg m-icon-big">
                            Push All Items <i class="m-icon-big-swapright m-icon-white"></i>
                        </a>
                    </div>
                </div>
                <div class="row magento-images">
                    <div class="col-md-4">
                    </div>
                    <div class="col-md-4">
                        <a href="/api-feeds/magento/images" class="btn blue btn-block btn-lg m-icon-big">
                            Push All Images <i class="m-icon-big-swapright m-icon-white"></i>
                        </a>
                    </div>
                </div>
                <br /><br />
                <div class="row">
                    <div class="col-md-12">
                        <table class="table table-striped table-bordered table-hover" id="kpiUpdates">
                            <thead>
                            <tr><th>ID</th>
                                <th>Sku</th>
                                <th>Attribute Field</th>
                                <th>New Attribute Value</th>
                                <th>Last Modified Date</th>
                                <th>Changed By</th>
                            </tr>
                            </thead>
                            <tbody>

                            <?php
                                foreach($this->sku as $index => $value) :
                                   if(isset($value['id'])):?>
                                    <tr>
                                        <td><?=$value['id']?></td>
                                        <td><?=$value['item']?></td>
                                       <?php array_shift($value);?>
                                        <td><?=ucfirst(str_replace('_',' ',current(array_keys($value))))?></td>
                                        <td><?=current($value)?></td>
                                        <td><?=$value['ldate']?></td>
                                        <td><?=$value['fName'] . ' ' . $value['lName'] ?></td>
                                    </tr>
                                    <?php endif;?>
                                <?php endforeach?>
                            </tbody>
                        </table>
                    </div>
                </div>
    </div>
</div>