<?php
/**
* Configuration file generated by ZFTool
* The previous configuration file is stored in module.config.old
*
* @see https://github.com/zendframework/ZFTool
*/
return array(
    'router' => array(
        'routes' => array(
            'amz' => array(
                'type' => 'Zend\Mvc\Router\Http\Literal',
                'options' => array(
                    'route'    => '/amz/',
                    'defaults' => array(
                        'controller' => 'Amz\Controller\Index',
                        'action'     => 'index',
                    ),
                ),
            ),
        ),
    ),
    'console' => array(
        'router' => array(
            'routes' => array(
                'review-process' => array(
                    'options' => array(
                        'route' => 'review',
                        'defaults' => array(
                            'controller' => 'Amz\Controller\Index',
                            'action'     => 'Index'
                        )
                    )
                )
            )
        )
    ),
    'controllers' => array('invokables' => array('Amz\Controller\Index' => 'Amz\Controller\IndexController')),
    'view_manager' => array('template_path_stack' => array(__DIR__ . '/../view')),
    
    'di' => array(
        'services' => array(
            'Amz\Model\ReviewTable' => 'Amz\Model\ReviewTable'))
    );
