<!DOCTYPE html>
<!--
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 2.3.1
Version: 1.1.2
Author: KeenThemes
Website: http://www.keenthemes.com/preview/?theme=metronic
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469
-->
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
    <meta charset="utf-8" />
    <title>Focus Intranet</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />
    <link href="/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/assets/css/metro.css" rel="stylesheet" />
    <link href="/assets/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" />
    <link href="/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="/assets/css/style.css" rel="stylesheet" />
    <link href="/assets/css/style_responsive.css" rel="stylesheet" />
    <link href="/assets/css/style_default.css" rel="stylesheet" id="style_color" />
    <link rel="stylesheet" type="text/css" href="/assets/gritter/css/jquery.gritter.css" />
    <!--    was: added 6/18/2014 for web editor styling-->
    <link href="/assets/css/font-awesome.min.css" rel="stylesheet">
    <link href="/assets/glyphicons/css/glyphicons.css" rel="stylesheet">
    <link href="/assets/glyphicons/css/style.css" rel="stylesheet">
    <!--    was:added 6/18/2014 for validation css-->
    <link href="/assets/jquery-validation/css/cmxform.min.css" rel="stylesheet">
    <!--was:added 6/18/2014 for date range picker styling-->
    <link rel="stylesheet" type="text/css" href="/assets/bootstrap-daterangepicker/daterangepicker.css" />
    <!--    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">-->
    <link rel="stylesheet" type="text/css" href="/assets/uniform/css/uniform.default.css" />
    <!--was: added 6/19/2014 for WYSIWYG-->
    <!--    <link href="assets/bootstrap-summernote/summernote.css" rel="stylesheet"  />-->
    <link rel="stylesheet" type="text/css" href="/assets/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css" />
    <link href="/assets/fullcalendar/fullcalendar/bootstrap-fullcalendar.css" rel="stylesheet" />
    <link href="/assets/jqvmap/jqvmap/jqvmap.css" media="screen" rel="stylesheet" type="text/css" />
    <link rel="shortcut icon" href="favicon.ico" />

    <!-------------------For file upload------------------------>
    <!-- BEGIN PAGE LEVEL STYLES -->
    <link href="/assets/global/plugins/jquery-file-upload/blueimp-gallery/blueimp-gallery.min.css" rel="stylesheet"/>
    <link href="/assets/global/plugins/jquery-file-upload/css/jquery.fileupload.css" rel="stylesheet"/>
    <link href="/assets/global/plugins/jquery-file-upload/css/jquery.fileupload-ui.css" rel="stylesheet"/>
    <!-- END PAGE LEVEL STYLES -->
    <!-------------------For file upload------------------------>



</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="fixed-top">
<!-- BEGIN HEADER -->
<div class="header navbar navbar-inverse navbar-fixed-top">
<!-- BEGIN TOP NAVIGATION BAR -->
<div class="navbar-inner">
<div class="container-fluid">
<!-- BEGIN LOGO -->
<a class="brand" href="http://zf2-client/">
    <img src="assets/img/logo.png" alt="logo" />
</a>
<!-- END LOGO -->
<!-- BEGIN RESPONSIVE MENU TOGGLER -->
<a href="javascript:;" class="btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse">
    <img src="assets/img/menu-toggler.png" alt="" />
</a>
<!-- END RESPONSIVE MENU TOGGLER -->



<!-- BEGIN TOP NAVIGATION MENU -->
<ul class="nav pull-right">



<!-- BEGIN NOTIFICATION DROPDOWN -->
<li class="dropdown" id="header_notification_bar">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="icon-warning-sign"></i>
        <span class="badge">0</span>
    </a>
    <ul class="dropdown-menu extended notification">


        <li>
            <p>User Notifications will go here</p>
        </li>
        <!--
        <li>
            <a href="javascript:;" onclick="App.onNotificationClick(1)">
            <span class="label label-success"><i class="icon-plus"></i></span>
            New user registered.
            <span class="time">Just now</span>
            </a>
        </li>
        <li>
            <a href="#">
            <span class="label label-important"><i class="icon-bolt"></i></span>
            Server #12 overloaded.
            <span class="time">15 mins</span>
            </a>
        </li>
        <li>
            <a href="#">
            <span class="label label-warning"><i class="icon-bell"></i></span>
            Server #2 not respoding.
            <span class="time">22 mins</span>
            </a>
        </li>
        <li>
            <a href="#">
            <span class="label label-info"><i class="icon-bullhorn"></i></span>
            Application error.
            <span class="time">40 mins</span>
            </a>
        </li>
        <li>
            <a href="#">
            <span class="label label-important"><i class="icon-bolt"></i></span>
            Database overloaded 68%.
            <span class="time">2 hrs</span>
            </a>
        </li>
        <li>
            <a href="#">
            <span class="label label-important"><i class="icon-bolt"></i></span>
            2 user IP blocked.
            <span class="time">5 hrs</span>
            </a>
        </li>
        <li class="external">
            <a href="#">See all notifications <i class="m-icon-swapright"></i></a>
        </li>

        -->
    </ul>
</li>
<!-- END NOTIFICATION DROPDOWN -->
<!-- BEGIN INBOX DROPDOWN -->
<li class="dropdown" id="header_inbox_bar">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="icon-envelope-alt"></i>
        <span class="badge">0</span>
    </a>
    <ul class="dropdown-menu extended inbox">
        <li>
            <p>Messages</p>
        </li>

        <!--
        <li>
            <a href="#">
            <span class="photo"><img src="./assets/img/avatar2.jpg" alt="" /></span>
            <span class="subject">
            <span class="from">Lisa Wong</span>
            <span class="time">Just Now</span>
            </span>
            <span class="message">
            Vivamus sed auctor nibh congue nibh. auctor nibh
            auctor nibh...
            </span>
            </a>
        </li>
        <li>
            <a href="#">
            <span class="photo"><img src="./assets/img/avatar3.jpg" alt="" /></span>
            <span class="subject">
            <span class="from">Richard Doe</span>
            <span class="time">16 mins</span>
            </span>
            <span class="message">
            Vivamus sed congue nibh auctor nibh congue nibh. auctor nibh
            auctor nibh...
            </span>
            </a>
        </li>
        <li>
            <a href="#">
            <span class="photo"><img src="./assets/img/avatar1.jpg" alt="" /></span>
            <span class="subject">
            <span class="from">Bob Nilson</span>
            <span class="time">2 hrs</span>
            </span>
            <span class="message">
            Vivamus sed nibh auctor nibh congue nibh. auctor nibh
            auctor nibh...
            </span>
            </a>
        </li>
        <li class="external">
            <a href="#">See all messages <i class="m-icon-swapright"></i></a>
        </li>
        -->
    </ul>
</li>
<!-- END INBOX DROPDOWN -->
<!-- BEGIN TODO DROPDOWN -->
<li class="dropdown" id="header_task_bar">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="icon-tasks"></i>
        <span class="badge">0</span>
    </a>
    <ul class="dropdown-menu extended tasks">
        <li>
            <p>New tickets maybe</p>
        </li>
        <!--
        <li>
            <a href="#">
            <span class="task">
            <span class="desc">New release v1.2</span>
            <span class="percent">30%</span>
            </span>
            <span class="progress progress-success ">
            <span style="width: 30%;" class="bar"></span>
            </span>
            </a>
        </li>
        <li>
            <a href="#">
            <span class="task">
            <span class="desc">Application deployment</span>
            <span class="percent">65%</span>
            </span>
            <span class="progress progress-danger progress-striped active">
            <span style="width: 65%;" class="bar"></span>
            </span>
            </a>
        </li>
        <li>
            <a href="#">
            <span class="task">
            <span class="desc">Mobile app release</span>
            <span class="percent">98%</span>
            </span>
            <span class="progress progress-success">
            <span style="width: 98%;" class="bar"></span>
            </span>
            </a>
        </li>
        <li>
            <a href="#">
            <span class="task">
            <span class="desc">Database migration</span>
            <span class="percent">10%</span>
            </span>
            <span class="progress progress-warning progress-striped">
            <span style="width: 10%;" class="bar"></span>
            </span>
            </a>
        </li>
        <li>
            <a href="#">
            <span class="task">
            <span class="desc">Web server upgrade</span>
            <span class="percent">58%</span>
            </span>
            <span class="progress progress-info">
            <span style="width: 58%;" class="bar"></span>
            </span>
            </a>
        </li>
        <li>
            <a href="#">
            <span class="task">
            <span class="desc">Mobile development</span>
            <span class="percent">85%</span>
            </span>
            <span class="progress progress-success">
            <span style="width: 85%;" class="bar"></span>
            </span>
            </a>
        </li>
        <li class="external">
            <a href="#">See all tasks <i class="m-icon-swapright"></i></a>
        </li>
        -->
    </ul>
</li>
<!-- END TODO DROPDOWN -->
<!-- BEGIN USER LOGIN DROPDOWN -->
<li class="dropdown user">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <!-- <img alt="" src="assets/img/avatar1_small.jpg" />-->
        <span class="username">haha<?=$this->firstname . ' ' . $this->lastname; ?></span>
        <i class="icon-angle-down"></i>
    </a>
    <ul class="dropdown-menu">
        <li><a href=""><i class="icon-user"></i> My Profile</a></li>
        <li><a href=""><i class="icon-calendar"></i> My Calendar</a></li>
        <li><a href=""><i class="icon-tasks"></i> My Tasks</a></li>
        <li class="divider"></li>
        <li><a href=""><i class="icon-key"></i> Log Out</a></li>
    </ul>
</li>
<!-- END USER LOGIN DROPDOWN -->
</ul>
<!-- END TOP NAVIGATION MENU -->
</div>
</div>
<!-- END TOP NAVIGATION BAR -->
</div>
<!-- END HEADER -->












<div class="page-container row-fluid">
    <!-- BEGIN SIDEBAR -->
    <div class="page-sidebar nav-collapse collapse">
        <!-- BEGIN SIDEBAR MENU -->
        <ul>
            <li>
                <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
                <div class="sidebar-toggler hidden-phone"></div>
                <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
            </li>
            <li>
                <!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->
                <form class="sidebar-search" action="" method = "POST">
                    <div class="input-box">
                        <a href="javascript:;" class="remove"></a>
                        <input type="text" placeholder="Search..." />
                        <input type="button" class="submit" value=" " />
                    </div>
                </form>
                <!-- END RESPONSIVE QUICK SEARCH FORM -->
            </li>
            <li class="start active ">
                <a href="">
                    <i class="icon-home"></i>
                    <span class="title">Dashboard</span>
                    <span class="selected"></span>
                </a>
            </li>

            <li class="has-sub ">
                <a href="javascript:;">
                    <i class="icon-bookmark-empty"></i>
                    <span class="title">Manage Content</span>
                    <span class="arrow "></span>
                </a>
                <ul class="sub">
                    <li ><a href="/search">Search</a></li>
                    <li ><a href="">Manage Categories</a></li>
                    <li ><a href="">Item Request</a></li>
                </ul>
            </li>

            <li class="has-sub ">
                <a href="javascript:;">
                    <i class="icon-bookmark-empty"></i>
                    <span class="title">Web Tools</span>
                    <span class="arrow "></span>
                </a>
                <ul class="sub">
                    <li ><a href="">IRA</a></li>
                    <li ><a href="">Add Items</a></li>
                    <li ><a href="">Help Desk</a></li>
                </ul>
            </li>
            <li class="">
                <a href="">
                    <i class="icon-calendar"></i>
                    <span class="title">Employee Info</span>
                </a>
            </li>
            <li class="">
                <a href="">
                    <i class="icon-camera"></i>
                    <span class="title">Seller Cloud</span>
                </a>
            </li>
        </ul>
        <!-- END SIDEBAR MENU -->
    </div>
    <!-- END SIDEBAR -->







    <!-- BEGIN PAGE -->
    <div class="page-content">








        <?php echo $this->content; ?>













    </div>
</div>
<!-- END CONTAINER -->
<!-- BEGIN FOOTER -->
<div class="footer">
    &copy; Focus Intranet
    <div class="span pull-right">
        <span class="go-top"><i class="icon-angle-up"></i></span>
    </div>
</div>


<!-- END FOOTER -->
<!-- BEGIN JAVASCRIPTS -->
<!-- Load javascripts at bottom, this will reduce page load time -->
<script src="/assets/js/jquery-1.8.3.min.js"></script>
<!--<script type="text/javascript" src="assets/bootstrap-toggle-buttons/static/js/jquery.min.js"></script>-->
<!--[if lt IE 9]>
<script src="assets/js/excanvas.js"></script>
<script src="assets/js/respond.js"></script>
<![endif]-->
<script src="/assets/breakpoints/breakpoints.js"></script>
<script src="/assets/jquery-ui/jquery-ui-1.10.1.custom.min.js"></script>
<!--<script src="/assets/js/jquery-1.11.1.min.js"></script>-->

<script src="/assets/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<!--<script src="assets/fullcalendar/fullcalendar/fullcalendar.min.js"></script>-->
<script src="/assets/bootstrap/js/bootstrap.min.js"></script>
<!--<script src="assets/js/jquery.blockui.js"></script>-->
<script src="/assets/js/jquery.cookie.js"></script>

<!-- WHO NEEDS THIS MAP SHIT?
<script src="assets/jqvmap/jqvmap/jquery.vmap.js" type="text/javascript"></script>
<script src="assets/jqvmap/jqvmap/maps/jquery.vmap.russia.js" type="text/javascript"></script>
<script src="assets/jqvmap/jqvmap/maps/jquery.vmap.world.js" type="text/javascript"></script>
<script src="assets/jqvmap/jqvmap/maps/jquery.vmap.europe.js" type="text/javascript"></script>
<script src="assets/jqvmap/jqvmap/maps/jquery.vmap.germany.js" type="text/javascript"></script>
<script src="assets/jqvmap/jqvmap/maps/jquery.vmap.usa.js" type="text/javascript"></script>
<script src="assets/jqvmap/jqvmap/data/jquery.vmap.sampledata.js" type="text/javascript"></script> -->
<!--<script src="assets/flot/jquery.flot.js"></script>-->
<!--<script src="assets/flot/jquery.flot.resize.js"></script> -->
<!--<script type="text/javascript" src="assets/bootstrap-daterangepicker/date.js"></script>-->
<!--<script type="text/javascript" src="assets/bootstrap-daterangepicker/daterangepicker.js"></script>-->


<script src="/assets/global/plugins/plupload/js/plupload.full.min.js" type="text/javascript"></script>
<script src="/assets/admin/pages/scripts/ecommerce-products-edit.js"  type="text/javascript"></script>
<script src="/assets/admin/pages/scripts/components-pickers.js" type="text/javascript"></script>
<script type="text/javascript" src="assets/gritter/js/jquery.gritter.js"></script>
<script type="text/javascript" src="assets/uniform/jquery.uniform.min.js"></script>
<script type="text/javascript" src="assets/js/jquery.pulsate.min.js"></script>
<!--<script type="text/javascript" src="/assets/data-tables/jquery.dataTables.js"></script>-->
<script type="text/javascript" src="/assets/data-tables/DT_bootstrap.js"></script>
<script type="text/javascript" src="/assets/global/plugins/datatables/media/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="/assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js"></script>
<!--was:added 6/19/2014 for WYSIWYG -->
<!--<script src="assets/bootstrap-summernote/summernote.min.js"></script>-->
<script src="/assets/ckeditor/ckeditor.js"></script>
<!--was:added 6/18/2014 for range picker -->
<script type="text/javascript" src="/assets/bootstrap-daterangepicker/daterangepicker.js"></script>
<script type="text/javascript" src="/assets/bootstrap-daterangepicker/date.js"></script>
<!--<script type="text/javascript" src="assets/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>-->
<!--<script type="text/javascript" src="assets/bootstrap-markdown/js/bootstrap-markdown.js"></script>-->
<!--<script type="text/javascript" src="assets/bootstrap-markdown/lib/markdown.js"></script>-->
<!--<script type="text/javascript" src="/assets/admin/pages/scripts/form-validation.js"></script>-->
<script src="/assets/global/scripts/metronic.js" type="text/javascript"></script>
<script src="/assets/admin/layout/scripts/quick-sidebar.js" type="text/javascript"></script>
<script src="/assets/admin/layout/scripts/layout.js" type="text/javascript"></script>

<script type="text/javascript" src="/assets/js/form_index.js"></script>
<script type="text/javascript" src="/assets/js/util.js"></script>
<!--was: added 6/18/2014 for validation -->
<!--<script type="text/javascript" src="/assets/jquery-validation/dist/jquery.validate.min.js"></script>-->

<!--<script type="text/javascript" src="assets/jquery-validation/dist/additional-methods.min.js"></script>-->
<script type="text/javascript" src="/assets/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js"></script>

<!-------------------For file upload------------------------>
<!-- BEGIN:File Upload Plugin JS files-->
<!-- The jQuery UI widget factory, can be omitted if jQuery UI is already included -->
<script src="/assets/global/plugins/jquery-file-upload/js/vendor/jquery.ui.widget.js"></script>
<!-- The Templates plugin is included to render the upload/download listings -->
<script src="/assets/global/plugins/jquery-file-upload/js/vendor/tmpl.min.js"></script>
<!-- The Load Image plugin is included for the preview images and image resizing functionality -->
<script src="/assets/global/plugins/jquery-file-upload/js/vendor/load-image.min.js"></script>
<!-- The Canvas to Blob plugin is included for image resizing functionality -->
<script src="/assets/global/plugins/jquery-file-upload/js/vendor/canvas-to-blob.min.js"></script>
<!-- blueimp Gallery script -->
<script src="/assets/global/plugins/jquery-file-upload/blueimp-gallery/jquery.blueimp-gallery.min.js"></script>
<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
<script src="/assets/global/plugins/jquery-file-upload/js/jquery.iframe-transport.js"></script>
<!-- The basic File Upload plugin -->
<script src="/assets/global/plugins/jquery-file-upload/js/jquery.fileupload.js"></script>
<!-- The File Upload processing plugin -->
<script src="/assets/global/plugins/jquery-file-upload/js/jquery.fileupload-process.js"></script>
<!-- The File Upload image preview & resize plugin -->
<script src="/assets/global/plugins/jquery-file-upload/js/jquery.fileupload-image.js"></script>
<!-- The File Upload audio preview plugin -->
<!--<script src="../../assets/global/plugins/jquery-file-upload/js/jquery.fileupload-audio.js"></script>-->
<!-- The File Upload video preview plugin -->
<!--<script src="../../assets/global/plugins/jquery-file-upload/js/jquery.fileupload-video.js"></script>-->
<!-- The File Upload validation plugin -->
<script src="/assets/global/plugins/jquery-file-upload/js/jquery.fileupload-validate.js"></script>
<!-- The File Upload user interface plugin -->
<script src="/assets/global/plugins/jquery-file-upload/js/jquery.fileupload-ui.js"></script>
<!-- The main application script -->
<!-- The XDomainRequest Transport is included for cross-domain file deletion for IE 8 and IE 9 -->
<!--[if (gte IE 8)&(lt IE 10)]>
<script src="/assets/global/plugins/jquery-file-upload/js/cors/jquery.xdr-transport.js"></script>
<![endif]-->
<!-- END:File Upload Plugin JS files-->
<script src="/assets/admin/pages/scripts/form-fileupload.js" type="text/javascript" ></script>

<!-------------------For file upload------------------------>

<script src="/assets/js/app.js"></script>
<script>
    jQuery(document).ready(function() {
        App.setPage("table_managed");  // set current page
        App.init(); // init the rest of plugins and elements
    });
</script>
<!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>
