<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
            Managed Attributes <small>Create and edit attributes</small>
        </h3>
        <ul class="page-breadcrumb breadcrumb">
            <li class="btn-group">
            </li>
            <li>
                <i class="fa fa-home"></i>
                <a href="/">Home</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="/">Manage Content</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="/content/attributemanagement">Attribute Management</a>
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>
<!-- END PAGE HEADER-->


<!-- BEGIN PAGE CONTENT-->

<br /><br /><br />
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet box purple-plum">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-globe"></i>Attribute Management
                </div>
                <div class="tools">
                    <a href="javascript:;" class="collapse">
                    </a>
                    <a href="#portlet-config" data-toggle="modal" class="config">
                    </a>
                    <a href="javascript:;" class="reload">
                    </a>
                    <a href="javascript:;" class="remove">
                    </a>
                </div>
            </div>
            <div class="portlet-body">
                <div class="table-toolbar">
                    <a class='btn green-haze' data-toggle='modal' href='#editModal'>Add New Attribute  <i class='fa fa-plus'></i></a>
                </div>
                <table class="table table-striped table-bordered table-hover" id="attributeTable">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Type</th>
                        <th>Last Updated</th>
                        <th>Last Changed by</th>
                        <th></th>
                    </tr>

                    </thead>

                    <tbody>
                    <tr>
                        <td>Front end Label</td>
                        <td>Front end input (user friendly values)</td>
                        <td>Last mod date (add to productattribute_lookup)</td>
                        <td>Last changed by (add to productattribute_lookup)</td>
                        <td><a class='btn green-haze' data-toggle='modal' href='#editModal'>Edit <i class='fa fa-plus'></i></a></td>
                    </tr>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!--------------------Modals--------------------------->
<div class="modal fade" id="editModal" tabindex="-1" role="crossModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Edit Website Assignment</h4>
            </div>
            <div class="modal-body">


              Add/edit form
               <br />
                Link to a pop up for second modal for options


            </div>
            <div class="modal-footer">
                <button type="button" class="btn default" data-dismiss="modal">Close</button>
                <input type="submit" class="btn blue" value="Save Changes">
                </form>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

