<?php
use Zend\Session\Container;

$loginSession= new Container('login');
$userData = $loginSession->sessionDataforUser;

$role = $userData['role'];
$acl = $this->viewModel()->getCurrent()->acl;
$aclPlugin = $this->viewModel()->getCurrent()->aclPlugin;


echo '<ul class="page-sidebar-menu" data-auto-scroll="true" data-slide-speed="200">
    <li class="sidebar-toggler-wrapper">
        <div class="sidebar-toggler">
        </div>
    </li>';



foreach ($this->container as $page){
    $hasChildren = $page->hasPages();

    if (!$hasChildren) {
        if (! $aclPlugin->checkAclByRoute($page->getRoute(), $acl)) {
            continue;
        }
        $active = '';
        $selected = 'arrow';

        if ($page->isActive()) {
            $active = 'start active';
            $selected = 'selected';
        }
        echo '<li class="'.$active.'">
        <a href="'.$page->getHref().'"><i class="icon-home"></i>
            <span class="title">'.$page->getLabel().'</span>
            <span class="'.$selected.'"></span>
        </a></li>';
    } else {
        if (! $aclPlugin->checkAclByRoute($page->getRoute(), $acl)) {
            continue;
        }
        //check if parent has active child
        $active = '';
        $skipPageRoute = true;
        foreach($page->getPages() as $child){
            if($child->isActive()){
                $active='active open';
            }
            if ($skipPageRoute && $aclPlugin->checkAclByRoute($child->getRoute(), $acl)) {
                $skipPageRoute = false;
            }
        }

        if ($skipPageRoute) {
            continue;
        }

        $selected = $page->isActive() ? 'selected' : 'arrow';

        echo '<li class="'.$active.'">
        <a href="'.$page->getHref().'"><i class="icon-home"></i>
            <span class="title">'.$page->getLabel().'</span>
            <span class="'.$selected.'"></span>
        </a>
        <ul class="sub-menu">';

        foreach($page->getPages() as $child){

            if (! $aclPlugin->checkAclByRoute($child->getRoute(), $acl)) {
                continue;
            }
            $active = '';
            $selected = 'arrow';

            if ($child->isActive()) {
                $active = 'start active';
                $selected = 'selected';
            }

            echo '<li class="'.$active.'">
        <a href="'.$child->getHref().'"><i class="icon-home"></i>
            <span class="title">'.$child->getLabel().'</span>
            <span class="'.$selected.'"></span>
        </a></li>';
        }


        echo '</ul></li>';
    }
}


?>


</ul>