<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in module.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return array(
<<<<<<< HEAD
    /* Removed
=======

//    'session'   =>  array(
//        'config'    => array(
//            'class' =>  'Zend\Session\Config\SessionConfig',
//            'options'   =>  array(
//                'name'  =>  'intranet'
//            ),
//        ),
//        'storage'   => 'Zend\Session\Storage\SessionArrayStorage',
//        'validators'    =>  array(
//            array(
//                'Zend\Session\Validator\RemoteAddr',
//                'Zend\Session\Validator\HttpUserAgent'
//            ),
//        ),
//    ),
//
>>>>>>> edit_form
    'doctrine' => array(
        'driver' => array(
            'search_entities' => array(
                'class' => 'Doctrine\ORM\Mapping\Driver\AnnotationDriver',
                'cache' => 'array',
                'paths' => array(__DIR__ . '/../src/Search/Entity')
            ),

            'orm_default' => array(
                'drivers' => array(
                    'Search\Entity' => 'search_entities')
            ),
        )
    ),
    */

    'router' => array(
        'routes' => array(
            'search' => array(
                'type' => 'Zend\Mvc\Router\Http\Literal',
                'options' => array(
                    'route'    => '/search',
                    'defaults' => array(
                        'controller' => 'Search\Controller\Search',
                        'action'     => 'index',
                    ),
                ),
            ),

            'form'  => array(
                'type'  => 'segment',
                'options'    => array(
                    'route' =>  '/form[/][/:sku]',
                    'constraints'   =>  array(
//                        'action'    =>  '[a-zA-Z]*',
//                        'id'    =>  '[0-9a-zA-Z]+',
                            'sku'    => '[a-zA-Z\d]+',
//                        'id'    =>  '[a-zA-Z]+',
//                        'id'    =>  '[0-9]+',
//                        'sku'    =>  '[a-zA-Z\d]+',
//                        'sku'    =>  '[^\W_]+',
                    ),

                    'defaults'  =>  array(
                        'controller'    => 'Search\Controller\Form',
                        'action'        =>  'index',

                    ),
                ),
            ),


            'quicksearch'  => array(
                'type'  => 'Zend\Mvc\Router\Http\Literal',
                'options'    => array(
                    'route' =>  '/search/quicksearch',

                    'defaults'  =>  array(
                        'controller'    => 'Search\Controller\Search',
                        'action'        =>  'quicksearch',

                    ),
                ),
            ),
        ),
    ),

    'controllers' => array('invokables' => array('Search\Controller\Search' => 'Search\Controller\SearchController',
                                                 'Search\Controller\Form'   => 'Search\Controller\FormController'
                                                )
    ),

//    'view_manager' => array(
//        'display_not_found_reason' => true,
//        'display_exceptions'       => true,
//        'doctype'                  => 'HTML5',
//        'not_found_template'       => 'error/404',
//        'exception_template'       => 'error/index',
//        'template_path_stack' => array(
//            __DIR__ . '/../view',
//        ),
//    ),

    'view_manager' => array(
        'template_path_stack' => array(
            __DIR__ . '/../view'
        ),
        'template_map'  =>  array(
            'search/form/index' =>  __DIR__ . '/../view/search/form/index.phtml',
            'search/search/index'   =>  __DIR__ . '/../view/search/search/index.phtml',
//            'search/form/404' =>  __DIR__ . '/../view/search/form/404.phtml',
        ),
//        'display_not_found_reason' => true,
//        'not_found_template'       => 'search/form/404',
    ),

//was 07/01/2014: this still appears to work
//    'di' => array(
//    'services' => array(
//        'Search' => 'Search\Model\SearchTable')),

);
